### ISSUE TITLE
Any chance of getting syntax highlighting?

### ISSUE THREAD

**Issue by Yantrio** [lunet-io/markdig#1]

**Comment by xoofx** [comment]
Hm not sure to follow, syntax highlighting where? for what?

**Comment by RoyiAvital** [comment]
Is this application I can run on my computer now?

**Comment by xoofx** [comment]
@RoyiAvital sorry, this is a .NET library, not a standalone application

Closing this issue as I don't have feedback on the original problem. You can reopen it if things are clarified, thanks!

**Comment by RoyiAvital** [comment]
I think he meant Syntax Highlighting like that (Using 3 ```):

> ```matlab
> <Some Matlab Code>
> ```
