### ISSUE TITLE
Full table syntax not supported

### ISSUE THREAD

**Issue by madskristensen** [lunet-io/markdig#10]
This syntax isn't treated as a table:

```md
|Milestone|Release Date|
|---------|------------|
|Beta7    | 24 Aug 2015|
|Beta8    | 21 Sep 2015|
|RC1      |    Nov 2015|
|RC2 Pre1 |    May 2016|
```

Using [BabelMark3](https://babelmark.github.io/?text=%7CMilestone%7CRelease+Date%7C%0A%7C---------%7C------------%7C%0A%7CBeta7++++%7C+24+Aug+2015%7C%0A%7CBeta8++++%7C+21+Sep+2015%7C%0A%7CRC1++++++%7C++++Nov+2015%7C%0A%7CRC2+Pre1+%7C++++May+2016%7C) I can see that some other parsers render it correctly, like this:

![image](https://cloud.githubusercontent.com/assets/1258877/16174749/c489da42-3586-11e6-9b56-83a904e7044b.png)

**Comment by xoofx** [comment]
Indeed, it looks like a trailing `|` on the header separator is making the table detection not working properly. For example this one is [working](https://babelmark.github.io/?text=%7CMilestone%7CRelease+Date%7C%0A%7C---------%7C------------%0A%7CBeta7++++%7C+24+Aug+2015%7C%0A%7CBeta8++++%7C+21+Sep+2015%7C%0A%7CRC1++++++%7C++++Nov+2015%7C%0A%7CRC2+Pre1+%7C++++May+2016%7C%0A):

```
|Milestone|Release Date|
|---------|------------
|Beta7    | 24 Aug 2015|
|Beta8    | 21 Sep 2015|
|RC1      |    Nov 2015|
|RC2 Pre1 |    May 2016|
```

Will dig into this.

**Comment by xoofx** [comment]
Should be fixed by commit 593bf08  
Version 0.5.3 on the way to NuGet
Thanks for the report!

**Comment by madskristensen** [comment]
Awesome. Thanks :)

**Comment by madskristensen** [comment]
I can't get this to work. Now it won't render a table with or without missing `|` characters

**Comment by xoofx** [comment]
Could you reopen another bug with an isolated case?

**Comment by madskristensen** [comment]
It's the exact same case. The following markdown is the only content in the file

```markdown
|Milestone|Release Date|
|---------|------------|
|Beta7    | 24 Aug 2015|
|Beta8    | 21 Sep 2015|
|RC1      |    Nov 2015|
|RC2 Pre1 |    May 2016|
```

This is the rendered output:

```html
<p>|Milestone|Release Date|
|&mdash;&mdash;&mdash;|&mdash;&mdash;&mdash;&mdash;|
|Beta7    | 24 Aug 2015|
|Beta8    | 21 Sep 2015|
|RC1      |    Nov 2015|
|RC2 Pre1 |    May 2016|</p>
```

**Comment by madskristensen** [comment]
Well, according to babelmark3, *Markdig (Extra)* seems to render it correctly. What does the *Extra* refer to and how can I use it?

**Comment by madskristensen** [comment]
This is my builder code:

```c#
var builder = new MarkdownPipelineBuilder()
    .UseEmojiAndSmiley()
    .UseSmartyPants()
    .UseAdvancedExtensions();

```

**Comment by madskristensen** [comment]
Ok, I narrowed it down and will be opening a new bug
