### ISSUE TITLE
Utility method for replacing built-in object renderer

### ISSUE THREAD

**Issue by Daniel15** [lunet-io/markdig#101]
Hello! I'm trying to use Markdig to replace MarkdownDeep. Currently I pre-process GitHub-style code fences via a regular expression, as MarkdownDeep does not support them natively. I'd like to remove this as Markdig is nice and supports code fences out-of-the-box, which is awesome. However, I want to output some different HTML to support my current configuration using highlight.js.

Currently I'm doing something like this to replace the built-in CodeBlockRenderer with my own one
```csharp
var originalCodeRenderer = renderer.ObjectRenderers.FindExact<CodeBlockRenderer>();
if (originalCodeRenderer != null)
{
	renderer.ObjectRenderers.InsertAfter<CodeBlockRenderer>(new HighlightCodeBlockRenderer());
	renderer.ObjectRenderers.Remove(originalCodeRenderer);
}
```

This works, but it seems a bit verbose. It would be nice to have a `ReplaceWith` utility method so I could do something like:
```
renderer.ObjectRenderers.ReplaceWith<CodeBlockRenderer>(new HighlightCodeBlockRenderer());
```

I guess I could just have an extension method for this though. Just an idea :)

Thanks for the awesome project!

**Comment by Daniel15** [comment]
This is the extension method I wrote, seems to be working fine so far:
```csharp
public static ObjectRendererCollection Replace<TOriginal>(
	this ObjectRendererCollection renderers, 
	IMarkdownObjectRenderer replacement
) where TOriginal : IMarkdownObjectRenderer
{
	var index = renderers.FindIndex(renderer => renderer.GetType() == typeof(TOriginal));
	if (index == -1)
	{
		throw new InvalidOperationException($"Could not find original object renderer for {typeof(TOriginal)}");
	}
	renderers.RemoveAt(index);
	renderers.Insert(index, replacement);
	return renderers;
}
```

Usage:
```
renderer.ObjectRenderers.Replace<CodeBlockRenderer>(new HighlightCodeBlockRenderer());
```

**Comment by xoofx** [comment]
It makes sense. Feel free to open a PR for [OrderedList.cs](https://github.com/lunet-io/markdig/blob/master/src/Markdig/Helpers/OrderedList.cs)

**Comment by Daniel15** [comment]
Thanks, I'll do that soon! :)

**Comment by xoofx** [comment]
Note that I have reverted back the changes related to VS2017 on master. Make sure to use the latest

**Comment by Daniel15** [comment]
Submitted as #103
