### ISSUE TITLE
Write a custom extension for markdig

### ISSUE THREAD

**Issue by al1b** [lunet-io/markdig#106]
I need to write some custom extentions form markdig, Since I haven't found any documention I need to ask is it possible?
If yes, How I can implement it?

**Comment by xoofx** [comment]
First, I need to know what do you want to do? 
Depending on this, you might not need to develop an extension. Many things can be done by just processing the Markdown AST returned by the parser.

If you need to develop an extension, the you need to know if it is going to be a block parser (like a paragraph, a fenced code block...etc.) or an inline parser (emphasis inside a paragraph...etc.), or you will need both.

While there is no documentation for developing an extension, markdig repository is coming with more than 20 extensions that are ranging from very simple one to much more complex, so you can easily learn from these, just my digging a bit into the sourcecode of the [extensions](https://github.com/lunet-io/markdig/tree/master/src/Markdig/Extensions), it is well organized and the code is quite commented, so it's not like you have just a black box API without any sourcecode to look at and you can't figure out how to do things.

**Comment by copernicus365** [comment]
Pointing out the code to the extensions was really helpful in pointing the way on this question, thanks.
