### ISSUE TITLE
EmphasisInlineRenderer ignores attributes

### ISSUE THREAD

**Issue by aKzenT** [lunet-io/markdig#108]
We have a custom parsing module that adds attributes to an EmphasisInline. Unfortunately the renderer does not write any attributes. Is there a specific reason for this? Could this be added?

Thanks!

**Comment by xoofx** [comment]
It is just an oversight ([here](https://github.com/lunet-io/markdig/blob/1bc9d9083c80733f7172997b3d61203d3efe67a1/src/Markdig/Renderers/Html/Inlines/EmphasisInlineRenderer.cs#L40)  is the missing writing attributes). PR Welcome!

**Comment by aKzenT** [comment]
Done!
