### ISSUE TITLE
Strong name?

### ISSUE THREAD

**Issue by cyotek** [lunet-io/markdig#11]
Hello,

I was looking at using Markdig as a replacement for CommonMark in one project and MarkdownDeep in another, however Markdig isn't strongly named. Does you have any plans on strong naming the Markdig library (or perhaps offer two packages, one signed, one unsigned (the way YamlDotNet does it), which will satisfy both stubborn-as-mules camps)?

Thanks;
Richard Moss

**Comment by jeremydmiller** [comment]
You can always use Strongnamer: https://github.com/dsplaisted/strongnamer

**Comment by xoofx** [comment]
Oh, nice this strongnamer, thanks @jeremydmiller 

@cyotek If you can live with strongnamer that would be great... I dislike strong naming specially for a library that provides a plugin API, as you have either to deal with assembly redirect or to "trick" your assembly/file version that will be different to the NuGet version to avoid assembly redirect binding (which is typically not great for minor versions, as you would still want your clients to work in the same way, without having to recompile anything)

**Comment by cyotek** [comment]
Thanks for the replies. I tried that strongnamer and can confirm it worked (at least as far as the example goes) but it's not a solution I'd like to use. At the same time I understand the reluctance of some library maintainers to add strong names (and I'm just as stubborn about using them it seems :))

**Comment by synhershko** [comment]
From a library author to another, please don't go the route of strong naming. I'd rather we strong arm the community.

**Comment by dotnetchris** [comment]
:-1: for strong naming the project

**Comment by tynorton** [comment]
Would be convenient for those of us with strong name requirements if there were 2 NuGet packages available. `MarkDig`, and `MarkDig.Signed`. Should satisfy everyone, no?

**Comment by dsplaisted** [comment]
> Would be convenient for those of us with strong name requirements if there were 2 NuGet packages available. `MarkDig`, and `MarkDig.Signed`. Should satisfy everyone, no?

This causes problems if there are other NuGet packages that depend on MarkDig.  Each of those NuGet packages would have to also publish a signed and nonsigned version, or else the version of MarkDig that you want to use might not work with packages that depend on it.

**Comment by gsaralms** [comment]
Would be convenient for those of us with strong name requirements if there were 2 NuGet packages available. MarkDig, and MarkDig.Signed. Should satisfy everyone, no?

This is a really great idea, we also want to use MarkDig but are currently blocked only because this is not signed

**Comment by xoofx** [comment]
@gsaralms  Yes, I will add a Markdig.Signed nuget package.

**Comment by gsaralms** [comment]
@xoofx : thanks a lot, it will help us a lot

**Comment by xoofx** [comment]
So the NuGet package [Markdig.Signed](https://www.nuget.org/packages/Markdig.Signed) should now provide signed assemblies.

**Comment by mdahamiwal** [comment]
Thanks a ton @xoofx :)
