### ISSUE TITLE
Nuget package is not up to date

### ISSUE THREAD

**Issue by clarkd** [lunet-io/markdig#114]
It looks like the Nuget package for markdig has not been update to include the recently merged Jira Links functionality yet. Is there anything I can do to assist here?

**Comment by xoofx** [comment]
I was just waiting for your feedback on PR #113 and was also super busy last week, super super busy this week, so I will probably try next week to push for a new release. 😉

**Comment by clarkd** [comment]
Ah, didn't realise you were waiting for feedback - it all looks good to me. OK, thanks :)
