### ISSUE TITLE
Is it possible to process markdown within a markdown table?

### ISSUE THREAD

**Issue by mloewent** [lunet-io/markdig#117]
Hello,

I have a markdown pipe table and each cell has a link within it. When I convert my markdown to HTML I get my table with raw markdown in it. Is this difficult to write an extension for?

**Comment by xoofx** [comment]
It should work, but there is likely a bug. Could you provide a very simple repro case?

**Comment by mloewent** [comment]
Did more testing and found that I cannot add headings or lists within a table. Code block, bold, and italics work as expected.
I think that is working as intended, may not want users to affect text size or list within a table. Thanks for your response.
