### ISSUE TITLE
HtmlBlockType.Comment has incorrect spans

### ISSUE THREAD

**Issue by madskristensen** [lunet-io/markdig#12]
When HtmlBlock.Type == HtmlBlockType.Comment, the span ends at the very end of the MarkdownDocument instead of the comment's closing tag. 

Example:

```markdown
<!-- this is great --> 
**hello**
```

The span length goes from the beginning `<!--` to the end of the document

**Comment by madskristensen** [comment]
Actually, it appears to happen when the comment block isn't on the first line of the document, but somewhere in the middle

**Comment by xoofx** [comment]
Fixed by commit be9c6fa. 
0.5.4 on the way
