### ISSUE TITLE
Add support for table caption in grid table

### ISSUE THREAD

**Issue by pearsonn** [lunet-io/markdig#120]
It would be great if there was a syntactic way of specifying a table caption to output a `<caption>` element within the table.

**Comment by xoofx** [comment]
Problem is that it is quite difficult to make Markdown syntax simple if we want to cover every features available in HTML... not not sure there is a plain syntax way to do this easily...

**Comment by christophano** [comment]
Would this not be a good use case for the existing `<figure>`/`<figcaption>` functionality?

I was about to suggest a change to remove the figure and move the `<figcaption>` contents to a `<caption>` for cases where the only child of a `<figure>` is a table but the [MDN Documentation](https://developer.mozilla.org/en/docs/Web/HTML/Element/caption) has its own recommendation.
> When the `<table>` element that is the parent of this `<caption>` is the only descendant of a `<figure>` element, use the `<figcaption>` element instead.

**Comment by maulwuff** [comment]
What about 
```
| First Header | Second Header | Third Header |  
| ------------ | :-----------: | -----------: |  
| Content      | **Cell**      | Cell         |  
| New section  | More          | Data         |  
[table caption]
```

taken from 
http://fletcherpenney.net/multimarkdown/
https://rawgit.com/fletcher/human-markdown-reference/master/index.html

**Comment by NeomMob** [comment]
I would be really happy to have it like MMD.

**Comment by SebastianRaffel** [comment]
A workaround could be to use [attribute extensions](https://github.com/lunet-io/markdig/issues/226#issuecomment-391947172) and generate `<caption>` from that afterwards. Works with markdig(advanced): [babelmark](https://babelmark.github.io/?text=%7Bcaption%3D%22my+Caption%22%7D%0A%7C+col1++%7C+col2+%7C%0A%7C+-----+%7C+----+%7C%0A%7C+cell1+%7C+cell2%7C%0A) 

```markdown
{caption="my Caption"}
| col1  | col2 |
| ----- | ---- |
| cell1 | cell2|
```

**Comment by xoofx** [comment]
Agreed, that can be workaround or done with a custom extension, but I don't see how we can come up with something that would work beyond Markdig.

Closing as wontfix
