### ISSUE TITLE
Disabling encoding of (some) national characters to HTML entities

### ISSUE THREAD

**Issue by cincuranet** [lunet-io/markdig#122]
When I have in MD character like `í`, it's encoded to `&#237;`. Correct, but unexpected, as this character can be in output as is. Surprisingly i.e. `š` is left untouched. 

Can I alter somehow this behavior? (And maybe out of curiosity, why is it behaving like this?)

**Comment by xoofx** [comment]
I can't reproduce this on [babelmark](https://babelmark.github.io/?text=When+I+have+in+MD+character+like+%C3%AD%2C+it%27s+encoded+to+%26%23237%3B). I don't remember the code doing this kind of transformations to the input char stream...

**Comment by cincuranet** [comment]
You're right. Sorry about that. DotLiquid filter is causing it.
