### ISSUE TITLE
File link not working

### ISSUE THREAD

**Issue by sibille** [lunet-io/markdig#127]
We are generating as part of our extension (Windows Template Studio) a markdown file that's opened in Visual Studio with the markdown editor. This file includes links to files on the disk. Links with white spaces are not shown correctly, and an investigation of the markdown editor team brought up an issue with markdig. 

### Replay

1. insert `[file1](C:/Users/John/Documents/Visual%20Studio%202017/Projects/BUPT-Projects/LICENSE)`
2. insert `[file2](LICENSE)`

### Go deeper
I've checked the generated links of both:

`file1: about:/C:/Users/John/Documents/Visual%20Studio%202017/Projects/BUPT-Projects/LICENSE
`
`file2: about:/C:/Users/John/Documents/Visual%2520Studio%25202017/Projects/BUPT-Projects/LICENSE` 

I suppose that markdig encode the % character into %25...

Can you help us with this?

The issue from Markdown editor is the madskristensen/MarkdownEditor#118

**Comment by xoofx** [comment]
From this [test on babelmark](https://babelmark.github.io/?text=%5Bfile1%5D(C%3A%2FUsers%2FJohn%2FDocuments%2FVisual%2520Studio%25202017%2FProjects%2FBUPT-Projects%2FLICENSE)) it seems that markdig correctly generates this...
