### ISSUE TITLE
[Question] Protection against XXS with user-generated input.

### ISSUE THREAD

**Issue by mloewent** [lunet-io/markdig#128]
Hi. I am wondering how I can protect against code execution using this library.
I want users to be able to add code snippets ```<script>alert("hi");</script>```, but to make sure they are encoded.
Currently if a user writes a code snippet without putting it in a ```code block``` the snippet will be executed. Is there any way this library can help protect against this?

Thanks.

**Comment by mloewent** [comment]
I believe I have solved this by using a library to sanitize the HTML output of markdig, using a whitelist of HTML tags. Will leave this issue open in case you have any input.

**Comment by xoofx** [comment]
Yes, it is recommended to use a sanitizer on the HTML output directly
