### ISSUE TITLE
First title ignored

### ISSUE THREAD

**Issue by ChaosPattern** [lunet-io/markdig#129]
When I tried to load the following md 

`# Es en castellano
This note demonstrates some of what [Markdown][1] is capable of doing.`

the first hashtag is ignored and it's converted as a paragraph

`<p>﻿# Es en castellano</p>\n<p>This note demonstrates some of what <a href=\"http://daringfireball.net/projects/markdown/\">Markdown</a> is capable of doing.</p>`

instead of 

`<h1>﻿ # Es en castellano</h1>\n<p>This note demonstrates some of what <a href=\"http://daringfireball.net/projects/markdown/\">Markdown</a> is capable of doing.</a>`

I'm using this piece of code

`Markdown.ToHtml(Text);`

thanks in advance

**Comment by cordialgerm** [comment]
@ChaosPattern was this resolved? I am running into the same issue with leading `#` being converted to paragraphs

**Comment by xoofx** [comment]
Could you reproduce it on https://babelmark.github.io ?

**Comment by ChaosPattern** [comment]
yes, was my mistake, in order to make some test I downloaded a md file from internet and the format was wrong (it has some bits were were wrong) I created new one in the notepad, and it's worked

**Comment by RyanfaeScotland** [comment]
Just stumbled across the same issue, discovered it was an encoding problem.

Visual Studio 2022 defaults to creating new text files in UTF8-BOM encoding, and this was leading to the mentioned issue of the first header being skipped. Switching the file's encoding to UTF8 resolved the issue.

Leaving this comment as a help for others with the same issue.
