### ISSUE TITLE
Using a Data URI as an image source doesn't work

### ISSUE THREAD

**Issue by JeroenVogelpoel** [lunet-io/markdig#132]
As shown [here](https://babelmark.github.io/?text=!%5Bhello%5D(data%3Aimage%2Fpng%3Bbase64%2CiVBORw0KGgoAAA%0AANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4%0A%2F%2F8%2Fw38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU%0A5ErkJggg%3D%3D)), Markdig does not render an image with a data URI as an actual image.

The expected output is an IMG tag with the SRC attribute set to the non-URI contents given in the example and an ALT text of 'hello'.

Would it be possible and realistic that the support of data URIs for images can be enabled in Markdig?

Thanks in advance!

**Comment by xoofx** [comment]
The problem is that CommonMark specs are not allowing any spaces/linebreaks in the URL. If you remove spaces from your data url, it will just work.  So I'm afraid that this cannot be supported.

**Comment by JeroenVogelpoel** [comment]
Yep, [removing the whitespace](https://babelmark.github.io/?text=!%5Bhello%5D(data%3Aimage%2Fpng%3Bbase64%2CiVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4%2F%2F8%2Fw38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg%3D%3D)) seems to fix it.

Works good for me, thanks!
