### ISSUE TITLE
Possible to handle protocol-less media?

### ISSUE THREAD

**Issue by sethreidnz** [lunet-io/markdig#135]
For example when using Contentful the media is returned as such:

```
//videos.contentful.com/4kxhtjjektmk/5jNKj0uP68Kw0uW0MIasOw/5628599e3424c29ba3a2ea2188d3d686/B80233.mp4
```

Would you accept a PR to handle this case if I can get it together? Or any thoughts on why this would be a bad idea?

**Comment by xoofx** [comment]
Not sure what do you mean by handle? Typically if you use this with a image url, it works correctly as seen on [babelmark](https://babelmark.github.io/?text=!%5BImage%5D(%2F%2Fvideos.contentful.com%2F4kxhtjjektmk%2F5jNKj0uP68Kw0uW0MIasOw%2F5628599e3424c29ba3a2ea2188d3d686%2FB80233.mp4))

**Comment by sethreidnz** [comment]
Sorry I wasn't clear enough. When i use that example there it gets
processed as an image tag. Not handled as a video tag as it does if I
simply add http: to the begining. Does that make sense?

**Comment by xoofx** [comment]
Yep, sounds reasonable, PR welcome.

**Comment by sethreidnz** [comment]
I'll try my best this weekend when I have time 👍
