### ISSUE TITLE
Using a subset of the markdown syntax

### ISSUE THREAD

**Issue by xt0rted** [lunet-io/markdig#136]
I want to use a subset of the markdown syntax (bold, italic, underline, strike, lists, paragraphs) and would like the rest of the syntax to render as plain text (`# Text` would render as-is instead of `<h1>Text</h1>`). Is there a way to adjust the settings so I can achieve this type of setup?

**Comment by xoofx** [comment]
You should be able to remove the relevant parsers from the `MarkdownPipelineBuilder`:

https://github.com/lunet-io/markdig/blob/c761fa22438e036f4b17fe64cab95ba1efd6122b/src/Markdig/MarkdownPipelineBuilder.cs#L27-L49

You might run into some trouble to disable some constructions that are hardcoded in some parsers (like the settext heading in the `ParagraphBlockParser`) as they would require a few changes in the code to make it possible. But nothing impossible...

**Comment by xt0rted** [comment]
@xoofx I finally got around to playing with this and was wondering if what I'm seeing is expected behavior since you said some things are hardcoded.

My parsers are setup like so:
```csharp
pipeline.BlockParsers.Clear();
pipeline.BlockParsers.Add(new Markdig.Parsers.ListBlockParser());
pipeline.BlockParsers.Add(new Markdig.Parsers.ParagraphBlockParser());

pipeline.InlineParsers.Clear();
pipeline.InlineParsers.Add(new Markdig.Parsers.Inlines.EmphasisInlineParser());
```

If my markdown is `---`, `___`, or `***` then it's rendered as `<hr />` even though the `ThematicBreakParser` isn't included. If I comment out the `ListBlockParser` then these aren't converted to html. Is this correct? Why would the `ListBlockParser` be creating `<hr />` elements when there's a parser for this which isn't even setup?

**Comment by xoofx** [comment]
> If my markdown is ---, ___, or *** then it's rendered as <hr /> even though the ThematicBreakParser isn't included. If I comment out the ListBlockParser then these aren't converted to html. Is this correct? Why would the ListBlockParser be creating <hr /> elements when there's a parser for this which isn't even setup?

Han, unfortunately, you are hitting a workaround in the code... that would require a bit modification to work. Currently, the `ListBlockParser` is accessing a singleton `ThematicBreakParser.Default`  while it should instead query for the ThematicBreakParser in its initialize method, and use it if it is present. It is not a big change, so PR welcome.

**Comment by xt0rted** [comment]
I'll be taking a look at this in the coming weeks hopefully.
