### ISSUE TITLE
UWP support

### ISSUE THREAD

**Issue by bardigolriz** [lunet-io/markdig#137]
I'd love to use Markdig for my app, appytext.net. 

At the moment, when I try to install the NuGet package I get the following error:

> Install-Package : System.Reflection.Emit.ILGeneration 4.0.1 provides a compile-time reference assembly for System.Reflection.Emit.ILGeneration on UAP,Version=v10.0.14393, but there is no run-time assembly compatible with 
> win10-arm-aot.
> At line:1 char:1
> + Install-Package Markdig -Version 0.13.1
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>  
> Install-Package : System.Reflection.Emit.ILGeneration 4.0.1 provides a compile-time reference assembly for System.Reflection.Emit.ILGeneration on UAP,Version=v10.0.14393, but there is no run-time assembly compatible with 
> win10-x64-aot.
> At line:1 char:1
> + Install-Package Markdig -Version 0.13.1
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>  
> Install-Package : System.Reflection.Emit.ILGeneration 4.0.1 provides a compile-time reference assembly for System.Reflection.Emit.ILGeneration on UAP,Version=v10.0.14393, but there is no run-time assembly compatible with 
> win10-x86-aot.
> At line:1 char:1
> + Install-Package Markdig -Version 0.13.1
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>  
> Install-Package : Package restore failed. Rolling back package changes for 'Appy Text'.
> At line:1 char:1
> + Install-Package Markdig -Version 0.13.1
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>

**Comment by xoofx** [comment]
This should be fixed by 001a99ab7787984a32117c25b335a343204044e4 and available as part of 0.13.2

**Comment by bardigolriz** [comment]
Thanks very much for promptly sorting this out!
