### ISSUE TITLE
Question about pipe tables without data rows. 

### ISSUE THREAD

**Issue by clintdavis77** [lunet-io/markdig#141]
We noticed something with the pipe table extension. If you put a table without a data row, in github it renders, but the markdig pipe table extension doesn't recognize it as a table. 

Example

|PIDM|ID|isProcessed
|---|---|---|

As a workaround, we just added a blank row after to force it to render like this.

|PIDM|ID|isProcessed
|---|---|---|
| |

Would you consider this a bug? It's not really specified according to pandoc pipe tables or anything else but it does work in github. I ask because I could probably find time to work on this and submit a PR but I don't want to waste my time.

**Comment by xoofx** [comment]
I believe it is a bug, don't remember exactly if I put this requirement in the code. Might be an oversight...

**Comment by xoofx** [comment]
This is fixed by commit 2147e43 and part of upcoming `0.13.4+`, thanks for the report.
