### ISSUE TITLE
AutoLinks option to open in new window

### ISSUE THREAD

**Issue by pebezo** [lunet-io/markdig#145]
Hi,

I noticed that JiraLinks has this feature, but not AutoLinks. Would you consider a PR for this?

Thanks.

**Comment by xoofx** [comment]
sure.

**Comment by pebezo** [comment]
When I open the solution with VS2015 (it looks like the .sln file was made by VS2015) I cannot load the Markdig project. I get:

```
Markdig.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.
```

If I try with VS2017, when compiling Markdig, I get:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	APPX3217	SDK folder containing 'UAP.props' for 'UAP 10.0.10240.0' cannot be located. See http://go.microsoft.com/fwlink/?LinkID=798187 for more information.	Markdig	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets	874	
```

Any ideas?

**Comment by xoofx** [comment]
You need most likely to install UWP components (10240) from the Visual Studio 2017 installer. Don't recall exactly the option... I should add a part in the readme about this.

**Comment by pebezo** [comment]
I installed Universal Windows Platform, but Windows 10 SDK (10.0.10240.0) was marked as optional. After checking / installing the option I'm now able to build. Thanks.

**Comment by pebezo** [comment]
JiraLinks has the `OpenInNewWindow` property `true` by default. As far as I can tell, the tests only check for the `true` value. 

In the case of AutoLink, setting a similar value to true would be a breaking change, so we should probably have it `false` by default. As far as testing, would you like a clone of AutoLinks.md that has `target="blank"` or just have hand written tests (i.e. not auto generated from .md files) that would test the new option on AutoLink?

Thanks
