### ISSUE TITLE
[Ejmoji Extension] URLs are being injected with emojis

### ISSUE THREAD

**Issue by madskristensen** [lunet-io/markdig#15]
From https://github.com/madskristensen/MarkdownEditor/issues/3

### Description
Urls are being injected with emojis.

### Steps to recreate
1. Add a plain url to the document such as `http://bing.com`

### Current behavior
The url is converted to `http😕/bing.com`

### Expected behavior
`:/` shouldn't be converted to an emoji

**Comment by xoofx** [comment]
I assumne that the extension Emoji is used? Similar to #13 Emoji extension is sometimes not working well with other extensions, that's why is not part of the advanced extensions. Workaround is to disable it for now.

**Comment by madskristensen** [comment]
Ok, I'll disable it for now

**Comment by xoofx** [comment]
Fixed by commit 087e7a6
