### ISSUE TITLE
LinkReferenceDefinition.Line never assigned

### ISSUE THREAD

**Issue by labreuer** [lunet-io/markdig#151]
I am very interested in markdig tracking the precise source code location for the syntax tree; unfortunately `LinkReferenceDefinition.Line` never seems set, perhaps because `LinkReferenceDefinition` is generated from an `ICharIterator`, which could be a `StringSlice`, which has no line # information. Was this by design?

If you're ok with `LinkReferenceDefinition.TryParse` accepting a `StringLineGroup.Iterator`, that would seem to suffice; it is not currently called with a `StringSlice`. I'm happy to put together a pull request.

**Comment by xoofx** [comment]
> I am very interested in markdig tracking the precise source code location for the syntax tree; unfortunately LinkReferenceDefinition.Line never seems set, perhaps because LinkReferenceDefinition is generated from an ICharIterator, which could be a StringSlice, which has no line # information. Was this by design?

afair no. It's just that line information was added after and a few places could have been missed during the process of adding the spans (I know for example that many extensions are not updated correctly...)

> If you're ok with LinkReferenceDefinition.TryParse accepting a StringLineGroup.Iterator, that would seem to suffice; it is not currently called with a StringSlice. I'm happy to put together a pull request.

I don't remember the details, but in `LinkReferenceDefinition.TryParse` we are already able to output spans for label..etc (via `LinkHelper.TryParseLinkReferenceDefinition`) so it should be possible to work with this already (as it is only using global Start position from beginning of file so it should be fine...). PR much welcome of course.

**Comment by MihaZupan** [comment]
Closing as resolved
