### ISSUE TITLE
Non breaking space after strong causing rending to fail

### ISSUE THREAD

**Issue by topherdavis** [lunet-io/markdig#157]
The string contains a non-breaking space (character code 160) immediately after `**time:**` and this results in `time:` not being rendered in a `strong` tag. 

Input:
```
**Check** **in/Check** **out:**  
**Check** **in** **time:** 5PM  
```

Output:
```
<p><strong>Check</strong> <strong>in</strong> **time:** 5PM<br /><strong>Check</strong> <strong>out</strong> <strong>time:</strong> Flexible</p>
```

Expected output:
```
<p><strong>Check</strong> <strong>in</strong> <strong>time:</strong> 5PM<br /><strong>Check</strong> <strong>out</strong> <strong>time:</strong> Flexible</p>
```

**Comment by topherdavis** [comment]
I was doing some more testing and this also causes a failure to render:

Input:

`**Unlimited-Fun®**®`

Output:

```
<p>**Unlimited-Fun®**®</p>
```

Expected:

```
<p><strong>Unlimited-Fun®</strong>®</p>
```

So it looks like it might be special characters in general.

Both of these also fail with `em` tags as well.

**Comment by xoofx** [comment]
Could you reproduce this on [babelmark](https://babelmark.github.io/)?

**Comment by topherdavis** [comment]
Yes I verified all of them against babelmark and locally, but having trouble reproducing now. I'm going investigate a little more. Thanks!

**Comment by topherdavis** [comment]
This isn't exactly the same as `**Unlimited-Fun®**®` but it is comparable.

https://babelmark.github.io/?text=*Unlimited-Fun%26%23174%3B*%26%23174%3B

**Comment by topherdavis** [comment]
I knew I wasn't crazy. I must have either missed I was pasting the html encoded version or chrome was doing something awesome for me.

Again not the same as `**Check** **in** **time:** 5PM `

https://babelmark.github.io/?text=**Check**+**in**+**time%3A**%26%23160%3B5PM++%0A

**Comment by xoofx** [comment]
Good, that's indeed a bug in Markdig.

**Comment by xoofx** [comment]
This should be part of upcoming 0.14.2

**Comment by xoofx** [comment]
Babelmark is updated

**Comment by topherdavis** [comment]
👍
