### ISSUE TITLE
Emphasis immediately followed by strong with non alpha numeric character causes strong to not render

### ISSUE THREAD

**Issue by topherdavis** [lunet-io/markdig#158]
Input:

`*Internet***:** WiFi`

Expected output:

`<em>Internet</em><strong>:</strong> WiFi`

Actual output:

`<em>Internet</em>**:** WiFi`

**Comment by xoofx** [comment]
I don't think this is a problem with Markdig. but it is part of the CommonMark specs. They changed recently this rules. As you can check on [babelmark](https://babelmark.github.io/?text=*Internet***%3A**+WiFi), all CommonMark compliant parsers are reporting the same output.

**Comment by xoofx** [comment]
You can check the [specs](http://spec.commonmark.org/0.28/#emphasis-and-strong-emphasis) It is quite difficult to dig into this. Feel free to bring this discussion to https://talk.commonmark.org/ if you have a more detailed question

**Comment by topherdavis** [comment]
I suppose it would fall under this example? 

http://spec.commonmark.org/0.28/#example-333

I'll work around this then.

I'm having trouble finding where `*Internet* **:** WiFi` with a space is specified?

Thanks!
