### ISSUE TITLE
Extension for bootstrap alert

### ISSUE THREAD

**Issue by stanac** [lunet-io/markdig#162]
Is it possible to extend bootstrap extension to support alerts?

Currently if we want to add alert in a document, we need to write html div tag with appropriate class.

It would be nice to have something like 
```
~~~danger
This is a danger warning
~~~
```
this converted to this
```
<div class="alert alert-danger">This is a danger warning.</div>
```

Syntax can be different, I am not too familiar with markdown specification, so I am not sure if this approach would be ok or not.

**Comment by xoofx** [comment]
Yes, I guess it should be feasible.

**Comment by xoofx** [comment]
It would likely use the existing [custom container extension](https://github.com/lunet-io/markdig/blob/master/src/Markdig.Tests/Specs/CustomContainerSpecs.md)

```
:::danger
This is a danger warning
:::
```

**Comment by stanac** [comment]
That looks interesting, I will check if it can be used out of the box, and if not how much effort would it be implement it.

**Comment by xoofx** [comment]
Not sure it will work out of the box (until css supports alias like  `danger` => `alert alert-danger`)
Otherwise it should be a very small change to the bootstrap extension to process CustomContainerBlock and change the class according to bootstrap classes

**Comment by cyotek** [comment]
@stanac I was just searching for similar functionality and I came across this issue, but also [this cheatsheet](http://www.digitaltapestry.net/posts/markdig-cheat-sheet). The example given in the cheatsheet was

```
:::{.alert .alert-info}
This is a Bootstrap alert.
:::
```

I tested this in some of my own content and it appears to be working absolutely fine with base Markdig and no third party extensions. The braces appear to be the key as when I originally tried using custom containers the content after the space was lost.

Clearly it's not quite as friendly as a simple "danger" label, but it does seem to get the job done - not sure if that's of any help to you or not.

**Comment by stanac** [comment]
@cyotek thanks for the find. I've bookmarked the cheatsheet. It's a generic solution I was looking for, so I'm closing the issue (@xoofx please reopen it if you disagree). @xoofx it would be nice to have a cheatsheet (this one or another similar) linked in the readme.
