### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by jerone** [lunet-io/markdig#163]
Where can I find the changelog / release notes for Markdig?

There is nothing in the Readme, no Changelog file and nothing in [Releases](https://github.com/lunet-io/markdig/releases).

**Comment by xoofx** [comment]
there is nothing, but versions are tagged, so if you really want to no, you can fetch git commits messages between versions

**Comment by xoofx** [comment]
If you check the history of [Markdig.csproj](https://github.com/lunet-io/markdig/blob/master/src/Markdig/Markdig.csproj) you will find some history..

It is a bit of a pain to maintain actually and this is not ideal. There is a changelog in this file. There is the `release` tabs in github (not used), there could be a `changelog.md`  file... (not used) etc.

What would be best? A `changelod.md` file?

**Comment by jerone** [comment]
Just noticed a very summier list of changes on the [NuGet](https://www.nuget.org/packages/Markdig/) page.

**Comment by xoofx** [comment]
If Nuget was working like Visual Studio Code, it would be much easier. I would just have to point to a `changelog.md` as part of the repo and everything would be linked

**Comment by jerone** [comment]
What about creating and maintaining the `Changelog.md` file and pointing to it in the `<PackageReleaseNotes/>` and the projects `Readme.md`.

**Comment by xoofx** [comment]
Yeah, but the problem is that when you consult the NuGet package online or via the Package Manager, it would not show up...

**Comment by jerone** [comment]
> Yeah, but the problem is that when you consult the NuGet package online...

https://www.nuget.org/packages/Microsoft.Azure.Mobile.Client.SQLiteStore/

**Comment by xoofx** [comment]
oh, right, why not, that would be at least a comprise...

Will try to do this in the future

**Comment by xoofx** [comment]
https://github.com/lunet-io/markdig/blob/master/changelog.md

**Comment by jerone** [comment]
Yes, I noticed it the other day. Thanks.
