### ISSUE TITLE
UseAutoLinks would be nice if it excluded punctuation like github

### ISSUE THREAD

**Issue by topherdavis** [lunet-io/markdig#165]
People will frequently terminate a sentence or join a sentence fragment by referring to url. Github excludes these punctuation marks from the autolink, but Markdig doesn't. It would be great if they were excluded from the autolink.

Examples of usage:

> I found it at http://www.travefy.com!

>I went to http://www.travefy.com, but didn't find what I was looking for.

In the end of url example Markdig does not match the github style:

Markdig style:
`http://www.travefy.com!` -> `<p><a href="http://www.travefy.com!">http://www.travefy.com!</a></p>`

Github style:
`http://www.travefy.com!` -> `<p><a href="http://www.travefy.com">http://www.travefy.com</a>!</p>`

In the intra-url example Markdig matches the github style:

Markdig style:
`http://www.travefy.com!/foo` -> `<p><a href="http://www.travefy.com!/foo">http://www.travefy.com!/foo</a></p>`

Github style:
`http://www.travefy.com!/foo` -> `<p><a href="http://www.travefy.com!/foo">http://www.travefy.com!/foo</a></p>`

**Comment by xoofx** [comment]
I agree. Currently no time to work on this, but PR welcome.

**Comment by xoofx** [comment]
Actually github has a [spec for autolink](https://github.github.com/gfm/#autolinks-extension-) but need also to follow this issue https://github.com/github/cmark/issues/27

**Comment by xoofx** [comment]
Fixed by commit 964538e
