### ISSUE TITLE
Images with Spaces

### ISSUE THREAD

**Issue by RickStrahl** [lunet-io/markdig#167]
When embedding image urls with spaces the images are not parsed and the raw markdown is embedded:

```md
This doesn't work (doesn't parse just embeds the markdown):
![](Markdown Monster.png)

This works:
![](Markdown%20Monster.png)

This works:
<img src="Markdown Monster.png" />
```

Looks like other parsers are split on handling this - some work some don't:

https://babelmark.github.io/?text=This+doesn%27t+work+(doesn%27t+parse+just+embeds+the+markdown)%3A%0A!%5B%5D(Markdown+Monster.png)%0A%0AThis+works%3A%0A!%5B%5D(Markdown%2520Monster.png)%0A%0AThis+works%3A%0A%3Cimg+src%3D%22Markdown+Monster.png%22+%2F%3E

**Comment by xoofx** [comment]
Yes, that's part of the CommonMark spec ([link destination](http://spec.commonmark.org/0.28/#link-destination))

> a nonempty sequence of characters that does not include ASCII space or control characters, and includes parentheses only if (a) they are backslash-escaped or (b) they are part of a balanced pair of unescaped parentheses. (Implementations may impose limits on parentheses nesting to avoid performance issues, but at least three levels of nesting should be supported.)

**Comment by RickStrahl** [comment]
Thanks for clarifying.

Still think this would be a nice thing to have work (and other parsers including PanDoc are putting it in), particularly because the underlying HTML supports it.  

Understand sticking to the spec though :-(

**Comment by xoofx** [comment]
> Still think this would be a nice thing to have work (and other parsers including PanDoc are putting it in), particularly because the underlying HTML supports it.

It is only the browsers that support them, but the HTML specs (i.e. with the underlying RFC for URI) actually don't allow spaces.  CommonMark allow also to specify a title attribute separated by a space right after the url like `[This is an example](http://example.com/ "Title Example")` which would fight against what you are looking for.

Moreover when you look at GitHub that is migrating to CommonMark, or in the .NET world, docfx also going to CommonMark, that's really not a good idea to encourage to replicate the legacy inconsistencies of browser behaviors.

**Comment by RickStrahl** [comment]
Fair enough. Thanks Alexandre.
