### ISSUE TITLE
AutoLinkParser option to remove mailto: in outputted text

### ISSUE THREAD

**Issue by stefandevo** [lunet-io/markdig#177]
With the AutoLinkParser the outputted text is fine for everything related to an url, this is readable by an user. But, for the an email address, it's strange there is a mailto: prefix in the visible text as well.
Could this be removed? Or optional?

**Comment by xoofx** [comment]
It is more a bug. That should be removed (also according to [GFM on babelmark](https://babelmark.github.io/?text=This+is+a+mailto%3Ajon%40c.com))
