### ISSUE TITLE
SmartyPants: even occurrences of double quotes are not recognized

### ISSUE THREAD

**Issue by AlekseyMartynov** [lunet-io/markdig#183]
0.14.8

```c#
var p = new MarkdownPipelineBuilder()
    .UseSmartyPants()
    .Build();

var html = Markdown.ToHtml("\"aaa\" - \"bbb\" - \"ccc\" - \"ddd\"", p);
```

`html` is `<p>&ldquo;aaa&rdquo; - &quot;bbb&quot; - &ldquo;ccc&rdquo; - &quot;ddd&quot;</p>
`

Note the alternation of `ldquo-rdquo` and `quot-quot`

**Comment by deanebarker** [comment]
I've found this too, but weirdly, it's alternating "sets" of quotes:

```
You spend a lot of time saying things like, “Where in
the world did all of this come from?” and "I don’t even
remember this" and “Who put this here?”
```

Three quoted phrases. The middle one ("I don't even remember this") retains straight quotes, while the other two have their quotes replaced.
