### ISSUE TITLE
Media extensions — add support for Yandex.Music & VK

### ISSUE THREAD

**Issue by leotsarev** [lunet-io/markdig#187]
Hi, I'm seeking to add embedding audio from VKontakte & Yandex.Music (pretty popular in Russia) and video from VKontakte.
I'm going to implement it myself, just checking with you if PRs are welcome.

**Comment by xoofx** [comment]
Yes. this should be part of the existing MediaLinks extension. Currently, the code is hardcoded, but if we could setup things through options instead, that would be fine (e.g a list of regex or similar), not sure if it is generalize-able, but you can check with your usecase and we will see what to do from there:

https://github.com/lunet-io/markdig/blob/0bb8139450794ee55491011c7110575fbc683efb/src/Markdig/Extensions/MediaLinks/MediaLinkExtension.cs#L63-L84
