### ISSUE TITLE
Find a way to regenerate Spec.cs when Specs\*.md changes

### ISSUE THREAD

**Issue by leotsarev** [lunet-io/markdig#192]
1. Change some spec (like Specs\MediaSpecs.md)
2. Rebuild project

Expected result: Specs.cs was automatically updated
Actual result: You have to manually run Specs.tt custom tool to perform that.

P.S. Also Specs.cs probably should be excluded from source control

**Comment by xoofx** [comment]
That's a limitation of `tt` files, so there is no real workaround for this.  `tt` files cannot be triggered at build time, they are design time only, so you need to go through the saving whenever there is an update to an indirect files.

A different way to do it would be to generate the tests on the fly, by loading the specs when launching the tests and create the tests from there, but in my experience, it can make the test loading more laborious and less reactive (and not displayable if you don't try to run the tests...)

The process of updating the specs is not common, so it is not that critical, and if you are aware of workflow in this case, you will not forget to resave the Specs.tt file

**Comment by leotsarev** [comment]
According to Google, there is __some__ solution 
https://stackoverflow.com/a/24274820/408666

I'm not explored this yet, so I just leave this link here for future me (or you or any other guy) to explore

**Comment by xoofx** [comment]
Yeah, sure you could run the T4 template process on your own, but frankly, that's a laborious process to setup, not really a typical usage with tt files. Again, once you know the workflow of updating the md specs files, it is not that annoying.

**Comment by leotsarev** [comment]
I don't like commiting generated file :-) 
But it probably my preference and it's for you to decide.

**Comment by xoofx** [comment]
> I don't like commiting generated file :-)

On that matter, I generally agree with this statement 😉 

If you want to try to generate the test on the fly by moving the specs loader from tt to the tests directly, you can try and see how it goes. As I have personally little bandwidth/interests on this matter, PR welcome.

**Comment by leotsarev** [comment]
See PR.
It seems to discover same number of tests.
I don't know of other way to test it.

**Comment by leotsarev** [comment]
Probably can be closed.
