### ISSUE TITLE
Use Markdig from PowerShell

### ISSUE THREAD

**Issue by datenschieber** [lunet-io/markdig#198]
I am trying to use Markdig from PowerShell. `Addtype .\Markdig.dll` runs without problems. The type `[Markdig.Markdown]` is available afterwards.

The problem is that I am not able to create a Markdig object. `New-Object Markdig.Markdown` fails with error message `New-Object : A constructor was not found. Cannot find an appropriate constructor for type Markdig.Markdown.`

`[Markdig.Markdown].GetConstructor()` says `Cannot find an overload for "GetConstructor" and the argument count: "0".`. It seems that Markdig.Markdown doesn't provide usable constructors.

Please provide a hint or an example for how to use Markdig from PowerShell. At the end I want to develop a PowerShell module that encapsulates Markdig with appropriate PowerShell advanced functions.

**Comment by xoofx** [comment]
> [Markdig.Markdown].GetConstructor() says Cannot find an overload for "GetConstructor" and the argument count: "0".. It seems that Markdig.Markdown doesn't provide usable constructors.
> Please provide a hint or an example for how to use Markdig from PowerShell. At the end I want to develop a PowerShell module that encapsulates Markdig with appropriate PowerShell advanced functions.

I barely use PowerShell so can't provide much help. But the class you are trying to use provides only static methods, so you can't create a new Mardown object obviously. Don't know the syntax in powershell but you should be able to access static methods likely.

**Comment by 0xfeeddeadbeef** [comment]
For example:

```powershell
[Markdig.Markdown]::ToHtml('**Markdown** `Text`')
```

**Comment by datenschieber** [comment]
That's it! Thanks for the hint! I am not familiar with C#...

The solution is easy now: `[Markdig.Markdown]::ToHtml("This is a text with some *emphasis*")`
