### ISSUE TITLE
[Question] How conver MarkdownDocument back to markdown

### ISSUE THREAD

**Issue by LSTANCZYK** [lunet-io/markdig#200]
I have MarkdownDocument instance and want to convert it back to markdown text after my document manipulation. How can i do that?

**Comment by xoofx** [comment]
You can use the NormalizeRenderer as it is used in Markdown.Normalize:

https://github.com/lunet-io/markdig/blob/eedfc3cd9cc4b8ccfa66d31fe401f0cc5b9582b6/src/Markdig/Markdown.cs#L54-L59

You have a call to a Parse method here, but you reusing your own MarkdownDocument, you can call then renderer yourself.

Note that saving back to MarkdownDocument supports mainly core CommonMark and very vew Markdig extensions (see #155)
