### ISSUE TITLE
Partial rendering

### ISSUE THREAD

**Issue by macaba** [lunet-io/markdig#204]
I'm trying to partially render markdown injected inline with existing paragraph content:

So I'd like:
`_italic_`

to render as:
`<em>italic</em>`

rather than:
`<p><em>italic</em></p>`

Is there an option to do this?

**Comment by xoofx** [comment]
There are no options for this. Just trim `<p>` and `</p>` after converting to HTML.
Not sure it might be just a little option to add but more work involved to bring a clean support for this, so if trimming is acceptable, it is recommended.

**Comment by macaba** [comment]
Thanks for the response, I'll trim manually.

```
if (markdown.StartsWith("<p>"))
    markdown = markdown.Substring(3);
if (markdown.EndsWith("</p>\n"))
    markdown = markdown.Substring(0, markdown.Length - 5);
```
