### ISSUE TITLE
Parsing <sup> and <sub> tags

### ISSUE THREAD

**Issue by amkuchta** [lunet-io/markdig#209]
While these may not be specifically markdown, some markdown standards (looking at you, GitHub) do not provide emphasis extensions for super and subscript, which forces users to rely on `<sup>` and `<sub>` tags.  Could MarkDig be updated to include support for this?

**Comment by xoofx** [comment]
> Could MarkDig be updated to include support for this?

Not sure to understand what markdig should include? Inline HTML are supported in markdig. Why markdig should have to parse sup/sub tags?

**Comment by amkuchta** [comment]
@xoofx do I have to do anything special to get the inline parser to work?

**Comment by xoofx** [comment]
If the value is correctly inside a paragraph/block line (and doesn't start it), afaik it works on almost any Markdown engine (Check [babelmark](https://babelmark.github.io/?text=This+is+x%3Csup%3E2%3C%2Fsup%3E))

**Comment by amkuchta** [comment]
> If the tags are correctly inside a paragraph/block line (and doesn't start it)

This may be my issue - my superscript tags are are on the ending of one line and the beginning of another.  Is there any way to update the library to allow for these items to be at the beginning / end of a line?

## Markdown Snippet
```text
* Security Content Automation Protocol (SCAP) content parsed via ACAS or the SCAP Compliance Checker (SCC)<sup>1</sup>
* Windows Automated Security Scanning Program (WASSP)  

---
<sup>1</sup>Parsing from additional sources is envisaged 
 
---
```

**Comment by amkuchta** [comment]
FYI, this is all in reference to https://github.com/Kryptos-FR/markdig.wpf/issues/10 (which you are tagged in)

**Comment by xoofx** [comment]
errata, starting at the line is working as well (check this [babelmark](https://babelmark.github.io/?text=%3Csup%3E1%3C%2Fsup%3EParsing+from+**additional**+sources+is+envisaged))

**Comment by amkuchta** [comment]
> Inline HTML are supported in markdig

For my own edification, with regards to the above quote, is inline HTML converted to markdown or left as HTML?  Looking at the "rendered" markdown, my inline `<sup>` tags are not converted to markdown.  According to @Kryptos-FR, he would rather not do any parsing of tags in MarkDig.WPF, but would rather relay solely on the output provided by MarkDig.  Can MarkDig be updated to parse `<sup>` and `<sub>` tags to `^` and `~`?

**Comment by xoofx** [comment]
> Can MarkDig be updated to parse <sup> and <sub> tags to ^ and ~?

Not really fan of the idea. If you really need this, you can always try to develop and use your own extension.
