### ISSUE TITLE
Markdown remains unparsed after pre element

### ISSUE THREAD

**Issue by roydukkey** [lunet-io/markdig#21]
I've updated from 0.2.1 to 0.5.9 and a markdown has broken. Below is my configuration.

	var builder = new MarkdownPipelineBuilder()
		.UseSoftlineBreakAsHardlineBreak() // broken w/ or w/o
		.Build()

Here is the a gist of the input and output, https://gist.github.com/roydukkey/630f431a89655ee6bb9c35f117b707e1.

**Comment by xoofx** [comment]
Ah! Sorry for this regression. This should be fixed a7cdb23. The `0.5.10` version is on the way

**Comment by xoofx** [comment]
Pushed a [PR](https://github.com/jgm/CommonMark/pull/409) to CommonMark specs to check for this case
