### ISSUE TITLE
[Question] `TextWriter.NewLine` is hard-coded to '\n' even when running on Windows

### ISSUE THREAD

**Issue by caioproiete** [lunet-io/markdig#211]
Hello!

Quick question: Is there a reason to [always uses `\n` for line-breaks instead of `Environment.NewLine`](https://github.com/lunet-io/markdig/blob/master/src/Markdig/Renderers/TextRendererBase.cs#L32), or is just preference?

Markdown files will typically contain fragments of content that - after being converted to HTML - are likely added as content to an HTML template (which itself has line-breaks), which can cause mixed line-endings if the HTML template uses `\r\n`.

**Comment by Kryptos-FR** [comment]
This should probably be an option (with a decent default value, like `Environment.NewLine`) so as to accommodate all scenarios.

**Comment by caioproiete** [comment]
@Kryptos-FR I agree that this should be configurable. I've submitted PR #214 to address that.

I'm curious on why `Environment.NewLine` is not the default, though...

**Comment by xoofx** [comment]
Thanks, PR #214 is merged, will publish a new package soon
