### ISSUE TITLE
AutoIdentifierOptions.GitHub should remove dots from anchor links

### ISSUE THREAD

**Issue by Jeavon** [lunet-io/markdig#218]
On GitHub `### Thing (v7.7.3+)` produces a anchor of `#thing-v773`
However when using markdig we get a anchor of `#thing-v7.7.3`

So  when AutoIdentifierOptions.GitHub is used the dots should be removed from the anchors

**Comment by xoofx** [comment]
this should be removed (typically all the links at [scriban](https://github.com/lunet-io/scriban/blob/master/doc/builtins.md#array-functions) was generated with Markdig) and looking at the markdig code:

https://github.com/lunet-io/markdig/blob/964538ec79270741463ba207fda6e151f527248e/src/Markdig/Helpers/LinkHelper.cs#L100-L115

it does keep only letter, digit, `-`, `_` but I don't see any `.`

**Comment by Jeavon** [comment]
@xoofx I'm not sure if I'm doing something wrong then, perhaps the attached helps?
![image](https://user-images.githubusercontent.com/1829920/37215430-d18a16f8-23af-11e8-8aa3-fb0f50c4309c.png)

**Comment by Jeavon** [comment]
Checked we weren't doing anything to the heading before passing into Markdig

![image](https://user-images.githubusercontent.com/1829920/37215732-b435702e-23b0-11e8-826a-577fa312268e.png)

**Comment by xoofx** [comment]
`UseAdvancedExtensions().UseAutoIdentifiers(...)` will not work as the extension is already added by `UseAdvancedExtensions`. Try to issue the `UseAutoIdentifiers` before

**Comment by Jeavon** [comment]
That's got it, thanks so much @xoofx !
