### ISSUE TITLE
Recommended JS front end editor for MarkDig?

### ISSUE THREAD

**Issue by Edddy** [lunet-io/markdig#22]
Do you know any client side JS library or plugin that play nice with MarkDig?

**Comment by xoofx** [comment]
Do you mean a JS syntax highlighting library? (Not code editor right?) I'm using [prism.js](http://prismjs.com/) which is compatible out-of-the-box with Markdig.

**Comment by Edddy** [comment]
No, no, basically a toolbar  that inserts the valid markdown artifacts
![screenshot_1](https://cloud.githubusercontent.com/assets/854168/16284388/47f3f96c-38a7-11e6-8013-4e1a8b6665e3.jpg)

**Comment by xoofx** [comment]
I see, but not sure to understand by "play nice with" then? Because you can use whatever editor with a Markdown content (SimpleMDE...etc.)... it is just that there are no editors that will support all extensions of Markdig, but that should not be a problem

**Comment by Edddy** [comment]
ok, thanks!
