### ISSUE TITLE
Support for image resizing

### ISSUE THREAD

**Issue by seanmcilvenna** [lunet-io/markdig#226]
It would be good if Markdig supported image re-sizing.
For example, some implementations of Markdown support the following:
`![](http://example.com/image.jpg =250x25)`
or
`![](http://example.com/image.jpg =250)`
The result would be:
`<img src="http://example.com/image.jpg" width="250" height="25" />`
and
`<img src="http://example.com/image.jpg" width="250" height="250" />`

**Comment by MisinformedDNA** [comment]
Yes, I was just looking for that as well. I read through the CommonMark spec and see that I can use this workaround:

```
<DIV STYLE="WIDTH:400px">

![](../images/asd.jpg)

</DIV>
```

But that's ugly and dirty.

**Comment by xoofx** [comment]
> It would be good if Markdig supported image re-sizing.
> For example, some implementations of Markdown support the following:
> `![](http://example.com/image.jpg =250x25)`

Not sure it is a good idea to add an extension for changing the CommonMark URL syntax... but you should be able to do this with the [special attributes extension](https://github.com/lunet-io/markdig/blob/master/src/Markdig.Tests/Specs/GenericAttributesSpecs.md). Check this on [babelmark](https://babelmark.github.io/?text=!%5B%5D(http%3A%2F%2Fexample.com%2Fimage.jpg)%7Bwidth%3D250+height%3D120%7D) with the `markdig (advanced)`  output:

```
<img src="http://example.com/image.jpg" width="250" height="120" alt="">
```

This syntax is supported by pandoc as well.

**Comment by MisinformedDNA** [comment]
The CommonMark syntax already allows for similar [syntax for links](https://spec.commonmark.org/0.28/#example-459)

```
[link](/uri "title")
```

We would just add similar functionality for images

```
![alt_text](/uri sizing)
```

But I see this is not widely supported either. So that's unfortunate.

That said, what is the difference between `markdig` and `markdig (advanced)`?

**Comment by seanmcilvenna** [comment]
So, why was this closed? Are we saying this is already supported by "markdig advanced"?
What is the solution that warrants closing this?

**Comment by xoofx** [comment]
> So, why was this closed? Are we saying this is already supported by "markdig advanced"?
What is the solution that warrants closing this?

- There is a already a way to do define resize through attributes. 
- I don't see the value of adding the syntax that is not used by any popular markdown processor. 
- You can always develop an extension to markdig in your own project if you really want this feature.

**Comment by MisinformedDNA** [comment]
@seanmcilvenna The solution is this

```
![](http://example.com/image.jpg){width=250 height=120}
```

(which, ironically enough, isn't supported by any other popular markdown parser either.)

I'm still baffled that there is no widely accepted way of doing this.

**Comment by seanmcilvenna** [comment]
do you mean that this is currently supported by markdig?

**Comment by xoofx** [comment]
> (which, ironically enough, isn't supported by any other popular markdown parser either.)
>
> I'm still baffled that there is no widely accepted way of doing this.

It is supported by pandoc, which is quite a strong markdown parser in the markdown ecosystem. The extension attributes in markdig is directly inspired from it.

> do you mean that this is currently supported by markdig?

What is supported is the attributes syntax, as described [above](https://github.com/lunet-io/markdig/issues/226#issuecomment-391947172)

If you really want to have your proposed syntax for your projects, it should not be a huge burden for you to develop an extension or to replace entirely the way links are parsed in markdig.

**Comment by MisinformedDNA** [comment]
@seanmcilvenna Yes, 

```md
![](http://example.com/image.jpg){width=250 height=120}
```

is supported by markdig. It is an example of the attribute syntax @xoofx is pointing you too.
