### ISSUE TITLE
Add Additional Font

### ISSUE THREAD

**Issue by PatrickRyder** [lunet-io/markdig#227]
This project seems to be exactly what I have been searching for except for one thing: I need to be able to specify at least two fonts.  This could be as simple as having one serif font and one sans serif.  I have tried creating a stylesheet.  This sort-of works, but I seem to lose all the other markdown support as soon as a I put my text in a `<span/>`.

I get the feeling I may be missing something simple.  Does what I am describing sound like something that can be achieved?

If I can solve this problem, I'd happily donate to future development.

Kind wishes ~ Patrick

**Comment by xoofx** [comment]
There is nothing in standard markdown that allows this. But you may be able to do workaround this with the extension [custom containers](https://github.com/lunet-io/markdig/blob/master/src/Markdig.Tests/Specs/CustomContainerSpecs.md) in markdig.
