### ISSUE TITLE
PowerShell Module

### ISSUE THREAD

**Issue by ephenix** [lunet-io/markdig#237]
Hello markdig team,

I wrote a **very** simple powershell cmdlet to expose this tool to PowerShell.

https://github.com/ephenix/MarkdownEx

In the future I plan to add granularity for enabling extensions, but for now it just enables advanced features.

I did not see any other implementations of this for PowerShell, so I think it may come in handy for some people.

Thanks,

Eric

**Comment by xoofx** [comment]
Nice, thanks for the feedback! (Note you can always send a PR here to add an entry to https://github.com/lunet-io/markdig#third-party-extensions )
