### ISSUE TITLE
HtmlCustomContainerRenderer does not honour EnableHtmlForBlock == false

### ISSUE THREAD

**Issue by ollynotice** [lunet-io/markdig#242]
We're building our pipeline with the `UseAdvancedExtensions` method as part of it and using this pipeline for rendering the same piece of text as both HTML and plaintext. For the plaintext we are setting up a new HtmlRenderer as:

```
 var renderer = new HtmlRenderer(writer)
                {
                    EnableHtmlForBlock = false,
                    EnableHtmlForInline = false
                };
```

However any content that 'HtmlCustomContainerRenderer' would pick up (i.e. between nested sets of 3 or more colons) is still rendered out as HTML. Having dug into the source I can see that 'HtmlCustomContainerRenderer' does not honour the 'EnableHtmlForBlock' bool that is set on the renderer, which every other extension we use does.

Any chance of this being honoured in a future release?

**Comment by xoofx** [comment]
Don't remember the details about this, just a send a PR and I will have a look at it.
