### ISSUE TITLE
Autolink does not recognize domain names followed by URL fragments query or port

### ISSUE THREAD

**Issue by yufeih** [lunet-io/markdig#258]
Due to #253, https://github.com#a, https://github.com?a, https://github.com:443 is no longer recognized as autolink. The [spec](https://github.github.com/gfm/#extended-autolink-path-validation) does not say about requiring a `/` after domain name, browsers can also handles these types of links just fine.

cc @MihaZupan

**Comment by MihaZupan** [comment]
I see, I think the only change needed here is to check for these characters along with the '/' check in LinkHelper. I'll do a PR when I get to a computer.

**Comment by xoofx** [comment]
Fixed by PR #260

**Comment by yufeih** [comment]
Thank you guys for the fix, awesome 🎁
