### ISSUE TITLE
Is AutolinkInline obsolete?

### ISSUE THREAD

**Issue by Kryptos-FR** [lunet-io/markdig#262]
When using markdig, in my WPF renderer, if I enable the autolink extension, I always get the links through a `LinkInline` and never through an `AutolinkInline`.

Should I remove the autolink-specific renderer?

If the autolinkInline is not be used anymore, maybe it would be nice to add the `[Obsolete]` attribute. But I might also be missing some other uses that I don't know about.

**Comment by xoofx** [comment]
Good question, I will have to take a look at this, don't remember much about the codebase for this part actually 😅

**Comment by Kryptos-FR** [comment]
It kinds of breaks it for email that are not recognized as such anymore.

**Comment by MihaZupan** [comment]
The naming might be confusing, but AutolinkInline is not what the AutoLink extension emits.

> Autolinks are absolute URIs and email addresses inside < and >. They are parsed as links, with the URL or email address as the link label.

> Autolinks can also be constructed without requiring the use of < and to > to delimit them, although they will be recognized under a smaller set of circumstances.

The first one is handeled by `AutolineInlineParser`, the second case by the AutoLink extension (`AutoLinkParser`).

AutolinkInline is used for `<url>` syntax only, while LinkInline is used for others.

I'm not sure if "AutolineInlineParser" was a typo.

**Comment by xoofx** [comment]
Yeah, it's a typo `AutolineInlineParser` 😅 

I don't remember why I didn't use AutoLink instead for the autolink extension. I haven't had the time to check the code base about this....

**Comment by Kryptos-FR** [comment]
OK. I'll keep both renderers and make sure they behave consistently.
Thanks for the explanation.
