### ISSUE TITLE
Best way to unescape HTML code in code blocks

### ISSUE THREAD

**Issue by pacman21** [lunet-io/markdig#263]
I have a need to unescape HTML code that we inject into our markdown, more or less, as a hack to get features that markdown generally doesn't support. What is the best way to go about this? I'm trying to create a custom extension, however I haven't been able to figure out how to modify the contents of the code block. I looked through the code and some of the documentation to try to find this, but haven't really ran into anything. 

Can you point in the right direction to find some documentation related to this?

**Comment by xoofx** [comment]
@pacman21 could you provide a more concrete example of what you are trying to achieve? markdig does support HTML tags (block and inlines) as per the CommonMark specs, so wondering exactly what is missing on your side?

**Comment by pacman21** [comment]
My apologies for the lack of examples provided and thank you for your swift assistance.

The markdown (value) I am passing in is:

```
// This is a code block. escaping the backticks. 
\`\`\`
This is a <span class="hl hl-1">test</span> code block
<span class="hl hl-1">This is a multiline code block Test</span><span class="hl hl-1"></span>
<span class="hl hl-1">Another line</span><span class="hl hl-1"></span>
<span class="hl hl-1">Ending the line</span>
\`\`\`
```

After I run the following command

```
var pipelineBuilder = new Markdig.MarkdownPipelineBuilder()
				.UsePipeTables()
				.UseBootstrap();

// CustomBootstrapExtension adds additional classes to the table element
pipelineBuilder.Extensions.Add(new CustomBootstrapExtension());

var pipeline = pipelineBuilder.Build();
value = Markdig.Markdown.ToHtml(value, pipeline);
```
The HTML output I receive is:

```
<pre><code>This is a    &lt;span class=&quot;hl hl-1&quot;&gt;test&lt;/span&gt;    code block
&lt;span class=&quot;hl hl-1&quot;&gt;This is a multiline code block Test&lt;/span&gt;&lt;span class=&quot;hl hl-1&quot;&gt;&lt;/span&gt;
&lt;span class=&quot;hl hl-1&quot;&gt;Another line&lt;/span&gt&lt;span class=&quot;hl hl-1&quot;&gt;&lt;/span&gt;
&lt;span class=&quot;hl hl-1&quot;&gt;Ending the line&lt;/span&gt;
</code></pre>
```

How do I get the span tags to render as spans instead of being escaped?

**Comment by Kryptos-FR** [comment]
Don't put them inside a code block but directly as-is.
https://babelmark.github.io/?text=This+is+a+%3Cspan+class%3D%22hl+hl-1%22%3Etest%3C%2Fspan%3E+code+block%0A%3Cspan+class%3D%22hl+hl-1%22%3EThis+is+a+multiline+code+block+Test%3C%2Fspan%3E%3Cspan+class%3D%22hl+hl-1%22%3E%3C%2Fspan%3E%0A%3Cspan+class%3D%22hl+hl-1%22%3EAnother+line%3C%2Fspan%3E%3Cspan+class%3D%22hl+hl-1%22%3E%3C%2Fspan%3E%0A%3Cspan+class%3D%22hl+hl-1%22%3EEnding+the+line%3C%2Fspan%3E

**Comment by xoofx** [comment]
The text inside a code block is rendered as literal text and escaped as required by the CommonMark specs.
You will have to hack something on your side if you want a different behavior.
