### ISSUE TITLE
:: error

### ISSUE THREAD

**Issue by jlcool** [lunet-io/markdig#265]
https://babelmark.github.io/?text=%7B%7Bc1%3A%3Aaaa%7D%7Dbbb%7B%7Bc2%3A%3Accc%7D%7D

**Comment by jlcool** [comment]
//UseCustomContainers()

**Comment by xoofx** [comment]
Could you explain what do you expect?

**Comment by jlcool** [comment]
I hope the colon is not escaped, but I have annotated the code to achieve it.

**Comment by xoofx** [comment]
Yes, you can configure markdig with whatever extensions that fits your usage. The default advanced plugins are going to setup a bunch of plugins that you might not need. If you don't need them, roll out your own setup of plugins, it's fine.
I guess I can close this issue then
