### ISSUE TITLE
Code block not adding new lines or pretty formatting

### ISSUE THREAD

**Issue by martinkearn** [lunet-io/markdig#268]
I have this markdown representing a C# code sample:

```c#
if (env.IsDevelopment())
{
    builder.AddUserSecrets<Startup>(false);
}
```

I'm using this code to convert it to HTML

```
var pipeline = new MarkdownPipelineBuilder()
    .UseYamlFrontMatter()
    .Build();
var html = Markdown.ToHtml(response, pipeline);
```

It is producing HTML with no new lines in it as follows

`<pre><code class="language-c#">  if (env.IsDevelopment())  {      builder.AddUserSecrets&lt;Startup&gt;(false);  }</code></pre>`

Is there an extension or some other solution to produce HTML code blocks that are nicely formatted?

**Comment by MihaZupan** [comment]
Copy-pasting your sample generates html with correct new lines for me

**Comment by Kryptos-FR** [comment]
How are your line endings in your C# code? Have a look at the `ConfigureNewLine` extension.

**Comment by martinkearn** [comment]
I'll try to setup a demo file which may be easier to demonstrate the problem. @Kryptos-FR where can I find this extensions? Is it a MarkDig extension?

**Comment by Kryptos-FR** [comment]
Looks like something is wrong on your end: all the line endings are removed. Are you sure you don't have some other post-processing?

Looking at https://babelmark.github.io/?text=%60%60%60c%23%0Aforeach+(var+thing+in+things)%0A%7B%0A++var+thisThing+%3D+thing%3B%0A%7D%0A%60%60%60 the result with markdig seems correct.

**Comment by martinkearn** [comment]
OK, thanks, it could be how I'm getting the raw Markdown. I'll investigate and post back here when I've figured it out

**Comment by martinkearn** [comment]
OK, I've resolved this now … it was nothing to do with MarkDig but the way I was getting my Markdown string (thanks @Kryptos-FR for the hint). The Markdown is on GitHub and I was getting the raw file using a GET request to <https://raw.githubusercontent.com/martinkearn/Content/master/Blogs/Test.md>. I'm now using the GitHub API to get the File object (GET request to <https://api.github.com/repos/martinkearn/Content/contents/Blogs/Test.md>) which includes a Base64 encoded version of its content. Once I've Base64Decoded that string and passed to MarkDig it all works fine. Thanks for the help. I hope this thread helps someone from the future.

**Comment by Kryptos-FR** [comment]
@martinkearn welcome. Thanks for providing the explanation as other people might stumble upon the same issue.
