### ISSUE TITLE
Triple emphasis support

### ISSUE THREAD

**Issue by XspeedPL** [lunet-io/markdig#269]
Hello,

As far as I know Markdig doesn't support italic and bold at once text by using triple emphasis.
Example: [commonmark.js dingus link](https://spec.commonmark.org/dingus/?text=***test***)
EmphasisInline class has only IsDouble property. Either IsTriple or Count property could be introduced.

Cheers

**Comment by MihaZupan** [comment]
It does, see https://babelmark.github.io/?text=***test***
If you look at the syntax tree returned when parsing this text, you will see that it outputs `EmphasisInline`(double) inside of an `EmphasisInline`(single).

**Comment by XspeedPL** [comment]
My bad, it does indeed work that way.
