### ISSUE TITLE
table formatting won't work

### ISSUE THREAD

**Issue by maulwuff** [lunet-io/markdig#27]
The pandoc pipe table example won't render as long as there is a `:` for right align or centered formatting in the header line.

works:
```
| abc | def | ghi |
|---|---|---|
| 1 | 2 | 3 |
```

doesn't work, doesn't render as html
```
| abc | def | ghi |
|:---:|---|---:|
| 1 | 2 | 3 |
```

version is 0.5.12

**Comment by xoofx** [comment]
Which extensions are you using?

**Comment by maulwuff** [comment]
```csharp
_pipeline = new MarkdownPipelineBuilder().UseAdvancedExtensions().Build();
```

**Comment by xoofx** [comment]
Hm, not sure I'm able to reproduce this with latest 0.6.0. Could you try? 

Typically it works on [babelmark3](https://babelmark.github.io/?text=%7C+abc+%7C+def+%7C+ghi+%7C%0A%7C%3A---%3A%7C---%7C---%3A%7C%0A%7C+1+%7C+2+%7C+3+%7C) (go down to check markdig (advanced))

**Comment by maulwuff** [comment]
yes, it works with 0.6.0 
thanks! ;)
