### ISSUE TITLE
<![CDATA[ breaks code blocks

### ISSUE THREAD

**Issue by clarkd** [lunet-io/markdig#273]
Using some CDATA blocks within a code sample seems to break Markdig. The rest of the markdown document does not render in our case.

e.g. trying to render the following markdown:

````
   # This is a test
   ```xml
   <failure><![CDATA[this is part 1 )]]></failure>
   <step><![CDATA[this is part 2]]></step>
   ```
   ````

Results in the following - as you can see, the second part is not rendered. 

![image](https://user-images.githubusercontent.com/3793131/49792454-b14f0600-fd2a-11e8-8866-3c91b4a5e783.png)

Any ideas? Is this a known issue?

**Comment by MihaZupan** [comment]
I can't reproduce this myself, are you using any custom extensions for the test?
[Babelmark](https://bit.ly/2SJFyU1)

**Comment by clarkd** [comment]
Thanks for the quick reply.

Our pipeline looks like this:

```
        return new MarkdownPipelineBuilder()
        .UseAdvancedExtensions()
        .UseEmojiAndSmiley()
        .UseBootstrap()
        .UseJiraLinks(new JiraLinkOptions("https://xxxxx.atlassian.net"))
        .Build();
```

**Comment by MihaZupan** [comment]
I get the following html with these as well:
```html
<h1 id="this-is-a-test">This is a test</h1>
<pre><code class="language-xml">&lt;failure&gt;&lt;![CDATA[this is part 1 )]]&gt;&lt;/failure&gt;
&lt;step&gt;&lt;![CDATA[this is part 2]]&gt;&lt;/step&gt;
</code></pre>
```

**Comment by Kryptos-FR** [comment]
Looks like you are applying a style. Might need to have a look at your CSS (or else), but as @MihaZupan mentioned, the generated HTML looks fine.

**Comment by xoofx** [comment]
@clarkd could you post the generated HTML? It is unlikely a problem in markdig (see babelmark), so as suggested, it might just be the syntax coloring extension messing with generated output?
