### ISSUE TITLE
Markdown renderer caused the string in { xxx } lost

### ISSUE THREAD

**Issue by Anduin2017** [lunet-io/markdig#279]
Markdown renderer caused the string in { xxx } lost.

When I try to convert the following markdown to HTML:

```markdown
{ HTTP_HOST }
```

Markdig will give me the following result:

```html
<p http_host>
</p>
```

But it seems other markdown converter will produce the following result:

```html
<p>
  { HTTP_HOST }
</p>
```

So how to make markdig to remain the content in the braces?

**Comment by Anduin2017** [comment]
My source code is 

```csharp
var pipeline = new MarkdownPipelineBuilder()
                .UseAdvancedExtensions()
                .Build();
// Convert from HTML to markdown
vm.Data.Content = Markdown.ToHtml(vm.Data.Content, pipeline);
```

It seems that I am using `UseAdvancedExtensions` extensions.

**Comment by xoofx** [comment]
That's the attribute extension causing this, you should not use it if you are using things like `{ xxx }`

**Comment by ltm0203** [comment]
Changed the code snippet

```
   var pipeline = new MarkdownPipelineBuilder()
                .UseAutoLinks()
                .UseBootstrap()
                .UseGridTables()
                .UsePipeTables()
                .Build();
            // Convert from HTML to markdown
            var result = Markdown.ToHtml(mymarkdown, pipeline);
```
Thank you very much for solving this problem
