### ISSUE TITLE
Requirements to build markdig?

### ISSUE THREAD

**Issue by Kryptos-FR** [lunet-io/markdig#28]
Hi.

I cloned markdig locally and try to open it with Visual Studio. I'm getting this error and the main project doesn't load:

> C:\Projects\markdig\src\Markdig\Markdig.xproj : error  : The imported project "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Projects\markdig\src\Markdig\Markdig.xproj

What do I need to do to fix this issue?
Could you add in the Readme file the dependencies of markdig?

Note: I'm using VS 2015 Community Edition

**Comment by xoofx** [comment]
Good point you need to install the [dotnet core RC2](https://www.microsoft.com/net/core)

On Monday, Markdig will be updated to RTM
