### ISSUE TITLE
Allow more leading # in ATX heading as a customization option

### ISSUE THREAD

**Issue by yufeih** [lunet-io/markdig#282]
We are using `TOC.md` to represent table of contents, It is a restricted markdown format that only allows several known markdown syntax, like links and ATX headers.

Sometimes these files can be very big and exceed [maximum leading count](https://github.com/lunet-io/markdig/blob/master/src/Markdig/Parsers/HeadingBlockParser.cs#L54) as defined by common mark spec, like [this one](https://raw.githubusercontent.com/MicrosoftDocs/VBA-Docs/master/api/TOC.md),

The ask is if it is possible to have an option in `HeadingBlockParser` that can override the default max leading count (6), so we can reuse `HeadingBlockParser` to parse our special TOC markdown.

Related https://github.com/dotnet/docfx/issues/3874

**Comment by xoofx** [comment]
Sure, via an extension and a slight change on `HeadingBlockParser`, PR welcome

**Comment by OsmondJiang** [comment]
Thanks a lot for quickly merging the PR 👍, it would be great if we can know when we can get a new nuget version?

**Comment by xoofx** [comment]
It should be come with upcoming `0.15.7` in a few minutes
