### ISSUE TITLE
ToHTML Problem

### ISSUE THREAD

**Issue by 1Zero3Tech** [lunet-io/markdig#289]
Hi,

Using Visual Studio 2017 Community, Build 15.9.5.  ASP .Net Core 2.2

I have a simple Markdown.cs file in the root directory of my project that looks like this:

```
using Markdig;

namespace MarkDig_Test
{
    public static class Markdown
    {
        public static string Parse(string markdown)
        {
            var pipeline = new MarkdownPipelineBuilder().UseAdvancedExtensions().Build();
            return Markdown.ToHTML(markdown, pipeline);
        }
    }
}
```

I am getting the following error in Visual Studio:

> Markdown does not contain a definition for ToHTML

I am confused by this...  Any guidance appreciated.  Thanks.

**Comment by MihaZupan** [comment]
It's `ToHtml` not `ToHTML`

**Comment by 1Zero3Tech** [comment]
> It's `ToHtml` not `ToHTML`

My Intellisense in Visual Studio does not offer a .ToHtml option.

Available options: 
Equals
Parse
ReferenceEquals

**Comment by MihaZupan** [comment]
Aw I see, you've names your class `Markdown` as well and you therefore hide the one implemented in Markdig

**Comment by 1Zero3Tech** [comment]
Oh my gosh... Yes.  

THANKS!
