### ISSUE TITLE
[Question] Alternative markdig renderer for wpf

### ISSUE THREAD

**Issue by neolithos** [lunet-io/markdig#290]
Hi @xoofx ,
are you interested in adding a alternative markdig renderer for wpf?

https://github.com/neolithos/NeoMarkdigXaml

This renderer uses more parts of the Xaml and Wpf-Framework, instead of doing its own stuff.

Greetings.

**Comment by xoofx** [comment]
Hi, you can send a PR to add a link to your project in the top `readme.md` if you want.
