### ISSUE TITLE
Abbreviation matching

### ISSUE THREAD

**Issue by MihaZupan** [lunet-io/markdig#296]
I've been looking at the `AbbreviationParser` and came accross this [discrepancy](https://talk.commonmark.org/t/abbreviations-longest-shortest-valid-match/3060) between different versions.

As a side-note, markdig currently doesn't match at all in cases like [this](https://babelmark.github.io/?text=*%5BFoo%5D%3A+foo%0A*%5BFoo+Bar%5D%3A+foobar%0A%0AFoo+B) due to how the `TextMatchHelper `works internally.

I'd be happy to fix this, just wanted to hear your thoughts on the commonmark issue first.

**Comment by xoofx** [comment]
You can go ahead with what you think is more relevant/safe/consistent. The `TextMatchHelper` is one of the helper classes that would definitely need to be revisited 👍

**Comment by MihaZupan** [comment]
I've written a version of TextMatchHelper as a [CompactPrefixTree](https://github.com/MihaZupan/SharpCollections).
Would you prefer I port it to markdig and add it as a helper class or add a NuGet reference (cross targets all platforms Markdig does)?

**Comment by xoofx** [comment]
> Would you prefer I port it to markdig and add it as a helper class or add a NuGet reference (cross targets all platforms Markdig does)?

Yeah, port it, I would like to avoid any dependencies.
