### ISSUE TITLE
Make HeadingBlockParser configurable

### ISSUE THREAD

**Issue by dustinmoris** [lunet-io/markdig#297]
Hi,

First of all this is a great library, I've been using it a lot for my blog and other projects and absolutely love it. I've got a use case where I would like to use Markdig to parse user entered markdown into HTML, but only a limited subset. One of the things which I would like to limit is the header tags (e.g. user should only be able to create h3, h4, h5, and h6, but not h1 and h2).

I would like to propose the following change in the [`HeadingBlockParser`](https://github.com/lunet-io/markdig/blob/master/src/Markdig/Parsers/HeadingBlockParser.cs):

Add an optional parameter to the constructor (this is pseudo code):

```csharp
private readonly HashSet<int> _allowedHeaders;

public HeadingBlockParser(HashSet<int> allowedHeaders = null)
{
    OpeningCharacters = new[] {'#'};
    _allowedHeaders = allowedHeaders != null
        ? allowedHeaders // Probably validate that it only contains valid values (1-6) here
        : new HashSet<int>() { 1, 2, 3, 4, 5, 6 };
}
```

And then change [this if statement](https://github.com/lunet-io/markdig/blob/master/src/Markdig/Parsers/HeadingBlockParser.cs#L72):

Before

```csharp
if (leadingCount > 0 && leadingCount <= MaxLeadingCount && (c.IsSpaceOrTab() || c == '\0'))
```

After

```csharp
if (_allowedHeaders.Contains(leadingCount) && (c.IsSpaceOrTab() || c == '\0'))
```

Then I could configure the `HeaderBlockParser` to limit the allowed headers via the constructor when setting up BlockParsers.

What do you think?

**Comment by MihaZupan** [comment]
I would think that it's not too common to not want h1, but want h3 for example. Therefore I believe that rather than changing the parser, post-processing the document AST to remove said headers would be more appropriate, since you can then decide whether to discard them all together or replace them with regular text

**Comment by xoofx** [comment]
I agree, otherwise someone else could come with a different rule here. It is quite straightforward to process the AST document afterwards and adapt it to your specific requirements.

**Comment by dustinmoris** [comment]
> I would think that it's not too common to not want h1, but want h3 for example

I think that is a very common scenario, because h1 has a special meaning in a HTML document or a particular HTML block. For example you shouldn't have more than one h1 in an `article` or a `hgroup`. If you want to display user entered markdown in a HTML block where you want to have control that there should be only one h1 then this is a VERY COMMON use case.

But nevertheless...

> post-processing the document AST to remove said headers would be more appropriate

If this is easy and fast then this would be good enough for me too. Have you got an example somewhere?

Thanks for the fast replies!

**Comment by dustinmoris** [comment]
> I agree, otherwise someone else could come with a different rule here.

My proposed suggestion would have given the flexibility to implement a different rule, because anyone could set any combination of headers into the constructor (e.g. `1, 2, 3` vs. `3, 4, 5, 6`, etc.), but I get your point, if you say that post processing is already the correct way of applying such rules in a fast and efficient way then I'm happy to do it. I didn't know about it.

**Comment by MihaZupan** [comment]
Something like this

```csharp
var pipeline = new MarkdownPipelineBuilder().UseAdvancedExtensions().Build();
var markdown = @"
# header 1

## header 2

### header 3

#### header 4

##### header 5

###### header 6
";

bool replaceWithText = true;
//                                    1      2      3     4     5     6
bool[] allowedHeadings = new bool[] { false, false, true, true, true, true };

var document = Markdown.Parse(markdown, pipeline);
foreach (var descendant in document.Descendants())
{
    if (descendant is HeadingBlock heading && !allowedHeadings[heading.Level - 1])
    {
        // The heading could be the first block
        var parent = heading.Parent ?? document;

        if (replaceWithText)
        {
            var literal = new LiteralInline(markdown.Substring(heading.Span.Start, heading.Span.Length));
            var inline = new ContainerInline();
            inline.AppendChild(literal);
            var paragraph = new ParagraphBlock
            {
                Inline = inline
            };

            for (int i = 0; i < parent.Count; i++) // Not the most efficient but it works
            {
                if (parent[i] == heading)
                {
                    parent.RemoveAt(i);
                    parent.Insert(i, paragraph);
                }
            }
        }
        else
        {
            parent.Remove(heading);
        }
    }
}

var writer = new StringWriter();
var renderer = new HtmlRenderer(writer);
pipeline.Setup(renderer);
renderer.Render(document);

string html = writer.ToString();
```

**Comment by xoofx** [comment]
Let's keep the code as it is today. You can either copy/paste the HeadingBlockParser in your own project and modify it, or go to the post-processing route, if you need a special handling. We can revisit this later if we have more people coming here looking for a similar use case.

**Comment by dustinmoris** [comment]
Ok thanks, I've went with copy pasting the current HeadingBlockParser and added my proposed changes and it works like a charm! Thanks for considering my proposal and keep up the great work!

**Comment by PeteFox** [comment]
I would like to give a +1 on @dustinmoris 's suggestion.

For use cases like Blogs or Support/Documentation pages, where multiple contributors write content intended for public facing pages, it's important from an SEO point of view, to only have one H1 tag, which describes the title of the document.

This H1 would typically be rendered outside the markdown by the wrapping page, and defined in a separate input field on the editing page. 

And yes, I know you could "just tell your users" to only use one H1 tag, and always place it in the top of the page - but that defeats the purpose of using something like Markdown, where you would want to restrict the editing/design options in order to create a more uniform layout and result markup.

I think it would make great sense to make an option that restricts the use of certain tags.
