### ISSUE TITLE
TextMatchHelper was removed — what's upgrade path?

### ISSUE THREAD

**Issue by leotsarev** [lunet-io/markdig#312]
TextMatchHelper was removed in #305  by @MihaZupan
It was useful for my private extension https://github.com/joinrpg/joinrpg-net/blob/master/Joinrpg.Markdown/LinkerParser.cs
new CompactPrefixTree is internal api, and I couldn't use it and benefit from wonderful optimizations.
Could you please make it public and/or introduce another public surface for the use case?

For now, I just copied TextMatchHelper into my code.

**Comment by xoofx** [comment]
Yes, it was not meant originally to be public but forgot to remove it. There are a couple of API that will be removed from the surface API (from the Helpers namespace for instance)

If you are looking for this API, I suggest you to use directly https://github.com/MihaZupan/SharpCollections from @MihaZupan

**Comment by leotsarev** [comment]
From my point of view, it was nice convenience api from extensions :-(
But I'll live with that decision
