### ISSUE TITLE
Help using Markdig with GitHub Flavored Markdown

### ISSUE THREAD

**Issue by mattvarghese** [lunet-io/markdig#313]
Hi Folks - 
### Question
I'm trying to find a Markdown parser that can handle [GitHub Flavored Markdown (GFM)](https://github.github.com/gfm/) in C#. Can Markdig do this? If yes, can you help me with what I am missing? 

Currently, my code looks like this:
<pre>
private string convertMarkDig(string markdown)
{
	MarkdownPipeline pl = new MarkdownPipelineBuilder().UseAutoIdentifiers(AutoIdentifierOptions.GitHub).Build();
	return Markdown.ToHtml(markdown, pl);
}
</pre>
This still does not handle GFM correctly. For example,
- using the "-" character to make an unordered list in GFM. 

If you can help me figure out how to use Markdig for GFM, that will be much appreciated!

### Broader Context
I'm working on implementing the [CDS Hooks](https://github.com/cds-hooks/docs) standard, and one of requirements is that the [details for display within a card](https://cds-hooks.org/specification/1.0/#card-attributes) is coded as Github Flavored Markdown. I need to convert this to HTML.

**Comment by MihaZupan** [comment]
> This still does not handle GFM correctly. For example,
>
>* using the "-" character to make an unordered list in GFM.

It does. Perhaps you did not use a space after '-'?

**Comment by mattvarghese** [comment]
@MihaZupan, the GFM snippet I used to test was the Raw source behind this file:
https://github.com/cds-hooks/docs/blob/master/docs/community.md
Output was:
<pre>
&lt;h1 id=&quot;community&quot;&gt;Community&lt;/h1&gt;
&lt;h2 id=&quot;get-involved&quot;&gt;Get Involved&lt;/h2&gt;
&lt;p&gt;There are several ways in which you can get involved with the CDS Hooks community.&lt;/p&gt;
&lt;p&gt;-Ask a question and participate in discussions via the&lt;a href=&quot;https://groups.google.com/forum/#!forum/cds-hooks&quot;&gt;CDS Hooks Google Group&lt;/a&gt;
-Chat via&lt;a href=&quot;https://zulip.org/&quot;&gt;Zulip&lt;/a&gt; at &lt;a href=&quot;https://chat.fhir.org&quot;&gt;https://chat.fhir.org&lt;/a&gt; in the &lt;em&gt;cds-hooks&lt;/em&gt; stream
-Contribute to the&lt;a href=&quot;https://github.com/cds-hooks&quot;&gt;code and documentation on Github&lt;/a&gt;
-Check out the&lt;a href=&quot;https://github.com/cds-hooks/docs/wiki/CDS-Services-for-testing&quot;&gt;CDS services available for testing&lt;/a&gt; and contribute your own.&lt;/p&gt;
&lt;h2 id=&quot;cds-hooks-sprint-program&quot;&gt;CDS Hooks Sprint Program&lt;/h2&gt;
&lt;h3 id=&quot;objectives&quot;&gt;Objectives&lt;/h3&gt;
&lt;p&gt;*Promote creation of clinical - grade service integrations(CDS Clients + CDS Services)&lt;/p&gt;
&lt;ul&gt;
&lt;li&gt;Gain implementation experience with real - world systems&lt;/li&gt;
&lt;li&gt;Refine the spec, balancing ease of use, flexibility, and stability&lt;/li&gt;
&lt;li&gt;Drive toward pilot deployments with the ability to measure results&lt;/li&gt;
&lt;/ul&gt;
&lt;h3 id=&quot;want-to-help-build-our-test-infrastructure&quot;&gt;Want to help build our test infrastructure?&lt;/h3&gt;
&lt;ul&gt;
&lt;li&gt;&lt;strong&gt;&lt;a href=&quot;https://github.com/cds-hooks/cds-hooks/labels/help%20wanted&quot;&gt;help - wanted issues&lt;/a&gt;&lt;/strong&gt;
*&lt;strong&gt;&lt;a href=&quot;https://github.com/cds-hooks/cds-hooks/milestones&quot;&gt;Proposed Milestones&lt;/a&gt;&lt;/strong&gt;&lt;/li&gt;
&lt;/ul&gt;
</pre>

Notice that the UL due to "*" work mostly (except for the space problem you mention), where as the UL due to "-" does not work.

**Comment by mattvarghese** [comment]
@MihaZupan, you are correct. That was the issue. Even though the source page had space between "-" and the first char, somehow, when copying into visual studio, that had gotten lost for me. 
Copied again, and it works correctly. Thanks 👍
