### ISSUE TITLE
No-ascii characters should be supported in AutoLinkInline

### ISSUE THREAD

**Issue by OpportunityLiu** [lunet-io/markdig#316]
https://babelmark.github.io/?text=%3Chttp%3A%2F%2F%E2%98%83.net%3F%E2%98%83%3E

Input:
```md
<http://☃.net?☃>
```

Expacted:
```html
<p>
  <a href="http://xn--n3h.net?%E2%98%83">http://☃.net?☃</a>
</p>
```

**Comment by OpportunityLiu** [comment]
as well as AutoLink

https://babelmark.github.io/?text=http%3A%2F%2F%E2%98%83.net%3F%E2%98%83+https%3A%2F%2Fcommonmark.org%2F

**Comment by xoofx** [comment]
Good catch, PR welcome!

**Comment by MihaZupan** [comment]
I implemented the `IsValidDomain` function according to [the GFM spec](https://github.github.com/gfm/#extended-www-autolink).

> A valid domain consists of alphanumeric characters, underscores (_), hyphens (-) and periods (.). There must be at least one period, and no underscores may be present in the last two segments of the domain.

That said, it seems that even GFM parses domain names like `http://☃.net?☃`  into `<a href="http://%E2%98%83.net?%E2%98%83" rel="nofollow">http://☃.net?☃</a>`.

@xoofx In reference to #252, should the test be changed from `alphanumeric characters` into `is not ascii punctuation`, as for example the snowman emoji falls under "other symbols", not alphanumerics?

**Comment by OpportunityLiu** [comment]
Although most of browsers could handle it, the correct result is `<a href="http://xn--n3h.net?%E2%98%83">http://☃.net?☃</a>`

https://en.wikipedia.org/wiki/Punycode

**Comment by MihaZupan** [comment]
I've implemented the changes needed for this, there is one minor problem tho.
`IdnMapping` class is not available for netstandard1.1 or for portable.
Currently I've put it in a `# if` region, where those two versions revert to percent-escaping.
@xoofx Would you be okay with non-consistent behavior for those legacy platforms in this case?
