### ISSUE TITLE
Autolinks match inside code blocks

### ISSUE THREAD

**Issue by Tyrrrz** [lunet-io/markdig#329]
Autolinks shouldn't match on text inside inline or fenced code blocks.

GitHub's behavior:

Normal: https://www.google.com/

Inline: `https://www.google.com/`

Fenced:
```
https://www.google.com/
```

**Comment by MihaZupan** [comment]
As far as I can tell, that's exactly what Markdig is doing
See [babelmark] (https://babelmark.github.io/?text=Autolinks+shouldn%27t+match+on+text+inside+inline+or+fenced+code+blocks.%0A%0AGitHub%27s+behavior%3A%0A%0ANormal%3A+https%3A%2F%2Fwww.google.com%2F%0A%0AInline%3A+%60https%3A%2F%2Fwww.google.com%2F%60%0A%0AFenced%3A%0A%60%60%60%0Ahttps%3A%2F%2Fwww.google.com%2F%0A%60%60%60)

**Comment by Tyrrrz** [comment]
This is embarrassing. You are right, sorry. This was caused by a client-side library. 😳
