### ISSUE TITLE
Support for admonition extension

### ISSUE THREAD

**Issue by mczachurski** [lunet-io/markdig#33]
Hi!

Could you add support for admonition extension? Admonition is simple markup which we can use to mark important part of documentation, it looks like this:

```
!!! note
    You should note that the title will be automatically capitalized.
```

Here is a more detailed description: [Admonition Extension](https://pythonhosted.org/Markdown/extensions/admonition.html). And here is an example how it should looks rendered on the page:

![capture](https://cloud.githubusercontent.com/assets/6191974/16446127/5c2a87f4-3de6-11e6-813a-100de6c801fe.PNG)

Example from [Read The Docs](http://read-the-docs.readthedocs.io/en/latest/theme.html) page .

I've tried to implement this using IMarkdownExtension (and BlockParser), however it's really hard without documentation (and BlockParser is not so obvious). 

Best regards,
Marcin.

**Comment by xoofx** [comment]
Why not using [custom containers](https://talk.commonmark.org/t/custom-container-for-block-and-inline/2051)?

```
:::note
You should note that the title will be automatically capitalized.
::: 
```
With proper CSS styling it should be possible to achieve the same result.

**Comment by xoofx** [comment]
@mczachurski did you finally find you way with the custom container extension?

**Comment by mczachurski** [comment]
@xoofx yes it work like a charm. Thanks.
