### ISSUE TITLE
CommonMark 0.29

### ISSUE THREAD

**Issue by MihaZupan** [lunet-io/markdig#330]
0.29 has been released, opening this issue to serve as a tracker for progress/related issues.

See
- [spec](https://spec.commonmark.org/0.29/)
- [changelog](https://github.com/commonmark/commonmark-spec/releases/tag/0.29)
- [diff](https://spec.commonmark.org/0.29/changes.html)
- [announcement post](https://talk.commonmark.org/t/ann-commonmark-0-29/3126)

**Comment by MihaZupan** [comment]
I've implemented most of the changes on the #327 branch.

## No Markdig changes needed
- Allow tabs in thematic breaks
- Unreferenced LinkReferenceDefinitions do not affect the output
- Info string is trimmed of ~~space~~ whitespace

## Changes implemented
- Info strings for tilde code blocks can contain backticks and tildes
- Meta html tag is no longer recognised
- An empty link destination may be specified using angle brackets (AutoLink and LinkReferenceDefinition)
- Setex headings with no content after a LinkReferenceDefinition are parsed as literals
- Decimal numeric character references consist of up to ~~8~~ 7 arabic digits
- Hexadecimal numeric character references consist of up to ~~8~~ 6 hexadecimal digits
- Interior spaces in backtick strings are not collapsed
- A backtick string is trimmed of a single front and back space if it is not a space-only string
- Delimiter runs can match if lengths of both are multiples of 3

## Breaking changes
- In `FencedBlockParserBase`, added an additional `char openingCharacter` argument to `InfoParserDelegate`.

## Yet to implement
- Changes to how indentation with list items is interpreted (tests 282, 283)

**Comment by xoofx** [comment]
We can close this one right?
