### ISSUE TITLE
Convert MarkdownDocument to plain text Markdown

### ISSUE THREAD

**Issue by asbjornu** [lunet-io/markdig#333]
Given a successfully constructed `MarkdownDocument`, how do I convert it to plain text Markdown code?

**Comment by MihaZupan** [comment]
You'd essentially be doing what `Markdown.Normalize` does:
https://github.com/lunet-io/markdig/blob/master/src/Markdig/Markdown.cs#L56-L61

Note that the `NormalizeRenderer` isn't complete, especially for extensions.

**Comment by asbjornu** [comment]
Thanks! This is related to #155 I suppose. I'll plow ahead and see where I end up.

**Comment by MihaZupan** [comment]
> This is related to #155 I suppose.

Exactly

**Comment by asbjornu** [comment]
As I show in #332, I'm using an extension for checklist support and it works just fine with `NormalizeRenderer`. 🎉 

Thanks again, @MihaZupan!
