### ISSUE TITLE
ToPlainText converts & to &amp;

### ISSUE THREAD

**Issue by yuri-martynov** [lunet-io/markdig#338]
Here is my pipeline setup

        MarkdownPipelineBuilder()
            .UseAdvancedExtensions()
            .UseEmojiAndSmiley()
            .UseSoftlineBreakAsHardlineBreak()
            .Build();

**Comment by OpportunityLiu** [comment]
Cannot reproduce with v0.17.0.
What's your input?

**Comment by MihaZupan** [comment]
I believe your change fixed this issue for 0.17, he was likely using 0.16
