### ISSUE TITLE
v0.17.0 is not deployed to nuget

### ISSUE THREAD

**Issue by OpportunityLiu** [lunet-io/markdig#339]
https://ci.appveyor.com/project/xoofx/markdig/builds/24457562
https://ci.appveyor.com/project/xoofx/markdig/builds/24457555

Seems that `appvoyer.yml` needs some modification?

**Comment by MihaZupan** [comment]
See [my comment](https://github.com/lunet-io/markdig/commit/9b2ec2e2e57b04f60d2a1eebf169df4e68747591#commitcomment-33496517), the release tag is simply missing the 'v' prefix.

**Comment by xoofx** [comment]
yeah, it was just an oversight, modified the appveyor to avoid the prefix
