### ISSUE TITLE
Extension for mermaid syntax

### ISSUE THREAD

**Issue by Hviid** [lunet-io/markdig#34]
I would like to propose an extension to support mermaid diagram syntax.
https://github.com/knsv/mermaid

I would also love to try doing a PR for it. But I think it would require a little guidance.

My initial thoughts could be something like:
{mermaid}(
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
)
Produces:
`<div class="mermaid">
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
</div>`

And then of course the mermaid JS needs to be included in the HTML file.

**Comment by Hviid** [comment]
Wow, totally awesome @xoofx.

**Comment by xoofx** [comment]
I have added a preliminary support for mermaid diagrams block by commit c6c2f58

It is using the regular fenced code block and detect if `mermaid` is used to output a div block instead of a pre/code block:

<pre>
```mermaid
graph TD;
A-->B;
A-->C;
B-->D;
C-->D;
```
</pre>

will output:

```html
<div class="mermaid">graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
</div>
```
Note that in order to fully support this in the Markdown Editor for Visual Studio, we will have to add support for layouts.

**Comment by janderson-bh** [comment]
I think this should actually render as

```
<pre class="mermaid">graph TD;
A-->B;
A-->C;
B-->D;
C-->D;
</pre>
```

**Comment by xoofx** [comment]
> I think this should actually render as

Yes, it was actually changed by this commit 090e6d791afbc4783839c71b71cde14f621f530d last year.

Not sure why I used div in the first place.

**Comment by janderson-bh** [comment]
That's strange, I'm using 0.43.0 and getting this output

<div class="lang-mermaid editor-colors"><div class="mermaid"><pre>   graph TD;
A-->B;
A-->C;
B-->D;
C-->D;</pre></div>
</div>

**Comment by xoofx** [comment]
> That's strange, I'm using 0.43.0 and getting this output

Please open a new issue with a small repro with exact code you are using to create this.
