### ISSUE TITLE
How to get YAML front matter?

### ISSUE THREAD

**Issue by lloydjatkinson** [lunet-io/markdig#343]
Given a markdown file, how do we get access to the YAML front matter?

```
---
title: "First"
date: 2019-05-26T14:30:08.8803451+00:00
tags: ["test1", "test2"]
---

# Hello World
```

For example I have:

	var pipeline = new MarkdownPipelineBuilder()
		.UseAdvancedExtensions()
		.UseYamlFrontMatter()
		.Build();

When I parse a markdown file I'd like to be able to also get the YAML front matter, probably as a dictionary (or even a plain string that we could use with a YAML parser...).

    var someString = Markdown.ToHtml(await streamReader.ReadToEndAsync(), pipeline);
    // <h1>Hello World</h1>
    // But how do we programmatically access the YAML?

**Comment by MihaZupan** [comment]
The Yaml extension does not do any yaml parsing, only detects its start and end. It does emit a `YamlFrontMatterBlock` that you can then access in the AST.
```c#
var pipeline = new MarkdownPipelineBuilder()
    .UseYamlFrontMatter()
    .Build();

StringWriter writer = new StringWriter();
var renderer = new HtmlRenderer(writer);
pipeline.Setup(renderer);

MarkdownDocument document = Markdown.Parse(markdown, pipeline);
var yamlBlock = document.Descendants<YamlFrontMatterBlock>().FirstOrDefault();

if (yamlBlock != null)
{
    string yaml = markdown.Substring(yamlBlock.Span.Start, yamlBlock.Span.Length);

    Console.WriteLine(yaml);
}

renderer.Render(document);
writer.Flush();
string html = writer.ToString();
```
