### ISSUE TITLE
Can the interpetation of code blocks formed from indented lines be turned off?

### ISSUE THREAD

**Issue by deanebarker** [lunet-io/markdig#348]
For a variety of pre-processing reasons, some of my lines of markdown end up with leading spaces. MarkDig interprets this as a code block, which I really don't want. I'd like it to be ignored.

Is there any way to shut off this specific rule?  I don't really have any code blocks in this particular body of content, and if I did, I could fence it with other blocks.

**Comment by MihaZupan** [comment]
Indented code blocks are handeled by the `IndentedCodeBlockParser`. Simply remove it from the pipeline.

```c#
var builder = new MarkdownPipelineBuilder()
    .UseAdvancedExtensions();

builder.BlockParsers.TryRemove<IndentedCodeBlockParser>();

var pipeline = builder.Build();

string html = Markdown.ToHtml(markdown, pipeline);
```

**Comment by deanebarker** [comment]
Wonderful, thank you.

For some reason, my version of Markdig didn't have `TryRemove`. I did this instead.
```
var indentedCodeBlock = builder.BlockParsers.FirstOrDefault(p => p.GetType() == typeof(IndentedCodeBlockParser));
builder.BlockParsers.Remove(indentedCodeBlock);
```

**Comment by ferventcoder** [comment]
Thanks!
