### ISSUE TITLE
Code coverage

### ISSUE THREAD

**Issue by MihaZupan** [lunet-io/markdig#351]
@xoofx Would you be okay with adding test code coverage to the repo?

I've tested the CI integration on [my fork](https://github.com/MihaZupan/markdig/commit/7d21f8b00356a2a2ccdf9427f6cf4522f4ce9463), exact platform doesn't really matter (currently coveralls).

It could be useful for locating untested sections / branches.

**Comment by xoofx** [comment]
Sure, I will provide the coveralls key (similar to what I did for [Zio](https://github.com/xoofx/zio/blob/master/appveyor.yml))
