### ISSUE TITLE
Hook into BlockProcesser with events

### ISSUE THREAD

**Issue by LukeTOBrien** [lunet-io/markdig#358]
Hello there,

I notice in your [BlockProcessor class](https://github.com/lunet-io/markdig/blob/master/src/Markdig/Parsers/BlockProcessor.cs) you have methods and properties that return the char indexes of the current Markdown element being processed, things like:

```csharp
        public int CurrentLineStartPosition { get; private set; }
        public int LineIndex { get; set; }
...
        public int Column { get; set; }
        public int Start => Line.Start;
```

Is there currently a way to hook into the `BlockProcessor` so I can build up a list of info objects that describe what has been processed?  
I would like a list of info object something like:

```csharp
public class Info
{
    int StartIndex
    int EndIndex
    string Tag
    string Content
}
```

So the following Markdown:

```Markdown
## Hello

**123**

# Goodbye
```

Would produce a List of Info objects like:

```cshap
[
    { StartIndex = 0, EndIndex = 8, Tag = "##", Content = "Hello" },
    { ..., Tag = "**", Content = "123" }
    { ..., Tag = "#", Content = "Goodbye" }
] 
```

The reason I want to do this is because I am creating a WYSIWYG editor, I have the Markdown (in a `<textarea>`) in one panel and the rendered HTML above.  
I want to find out which element the user has clicked on when they click in the Markdown `<textarea>`.

> Note: The GUI is in html and the Markdig compilation in done via ajax call to C# WebAPI.

If this is hard to understand, but hopefully you get the idea ;-)

**Comment by MihaZupan** [comment]
> Is there currently a way to hook into the BlockProcessor so I can build up a list of info objects that describe what has been processed?

No. It would also be hard to add in the form you suggest due to the `Tag`.

However, when you parse some markdown, you can look at the `MarkdownDocument` that contains all the parsed elements. All elements (`MarkdownObject`s) also contain a `Span` field. You can therefore find the element in the document that matches the clicked region. Make sure you tell the pipeline to `UsePreciseSourceLocation`.


In your case this would look like:
```c#
string markdown = @"## Hello

**123**

# Goodbye";

var builder = new MarkdownPipelineBuilder()
    .UsePreciseSourceLocation();

var pipeline = builder.Build();

MarkdownDocument document = Markdown.Parse(markdown, pipeline);

var obj = GetHoveredOverObject(document, 13);
// obj is EmphasisInline

string content = markdown.Substring(obj.Span.Start, obj.Span.Length);
// **123**
```

I wrote a quick function that will extract the smallest/deepest object matching the index.

```c#
public static MarkdownObject GetHoveredOverObject(MarkdownDocument document, int index)
{
    var block = document.Descendants<Block>()
        .FirstOrDefault(b => b.Span.Start <= index && b.Span.End >= index);

    if (block != null)
    {
        if (block is LeafBlock leaf)
        {
            var inline = TryGetHoveredOverInline(leaf.Inline, index);
            if (inline != null)
            {
                return inline;
            }
        }

        return block;
    }

    return document;
}

private static Inline TryGetHoveredOverInline(ContainerInline container, int index)
{
    if (container is null)
        return null;

    var child = container.FirstChild;

    while (child != null)
    {
        if (child.Span.Start <= index && child.Span.End >= index)
        {
            if (child is ContainerInline subContainer)
            {
                var candidate = TryGetHoveredOverInline(subContainer, index);
                if (candidate != null)
                {
                    return candidate;
                }
            }

            return child;
        }
        child = child.NextSibling;
    }

    return null;
}
```

**Comment by LukeTOBrien** [comment]
Thanks for giving my a full code example!

I managed to modify your code a little for my needs and I have manage to create the list of info object in a kinda way  that I can work with in the client-side.

Thank you for your help!
