### ISSUE TITLE
Header character within blockquotes

### ISSUE THREAD

**Issue by LukeTOBrien** [lunet-io/markdig#364]
Version: 0.17.1

Hi there,

I just wondered if you're done testing with header character (`#`) within blockquotes?

Just now I compiled a presentation I have written to teach kids about programming, in one of my slides I have:
```markdown
> In C# we can do this: 
```

It seems the `#` was compiled into `<h1>` when I wanted it ignored as text.  
Even if I surrond the has in code block ```` it still compiles it as `<h1>` when it should be text.

Can you have a look at replicating this?

**Comment by MihaZupan** [comment]
I can't reproduce this for the given input, see [babelmark](https://babelmark.github.io/?text=%3E+In+C%23+we+can+do+this)

**Comment by LukeTOBrien** [comment]
You are quite right, [I just created a .NET Fiddle](https://dotnetfiddle.net/avFITy) and it seems to be okay.  
Perhaps it is a problem on my side, I am doing some processing as well as Markdown compilation.

I will close the issue.
