### ISSUE TITLE
Multi-line table entry or way to ignore line break.

### ISSUE THREAD

**Issue by qqkookie** [lunet-io/markdig#366]
For example, table with three rows and two columns each.
```
 Header One  | Header Two   
 -------------- | -----------------------------
 Row1           | This is This is very, very very very very longooooooooo ooooooooooooooooo line. 
 Row2          | Short entry
```
I like to break "This is very very loooo...ng entry" into two source line.  

```
 Header One  | Header Two   
 -------------- | -----------------------------
 Row1           | This is This is very, very very very very 
longooooooooo ooooooooooooooooo line. 
 Row2          | Short entry
```

This does not mean that it will break line in display (like \<BR\>) Just markdown parser will ignore newline after the last "very" and continue accept next line as part of the table entry. This is more consistent behavior for markdown format which largely treats single line break as space in source. 
This can be done by adding "line continuation" back slash (\\) as character escape or some other mean like  enclosing the multi-line entry or whole the table itself with bracket ({{ entry... }}) or any similar way. 

TRDR: There must be some way to  accept long table entry spreaded in 2 lines as single table entry.

**Comment by xoofx** [comment]
afaik, none of the existing markdown parser table implementation support this, so we won't try to support this for now.
