### ISSUE TITLE
MarkdownExtensions

### ISSUE THREAD

**Issue by generateui** [lunet-io/markdig#369]
Hi guys! I have opened up [MarkdownExtensions](https://github.com/generateui/MarkdownExtensions). The idea is to develop Markdown extensions which include css, js and access to local resources (i.e. excel files, sql databases, any program really). 

It's build on top of Markdig. The idea is to enhance Markdig and supplement Markdig and *not* to compete with Markdig. I feel some extensions are out-of-place in Markdig; in particular the diagram (nomnoml and mermaid) extensions. The problem is that these extensions require CSS and JS to function which Markdig (rightfully) does not support.

So the basic idea behind it is for simple Markdown by all means use Markdig, but if you want more complex document generation spewing out css/js and utilizing local data sources: use MarkdownExtensions.

Please let me know what you think. The state of the library is still experimental. Alexandre: I realize your fast constructs of Markdig are horribly broken with MarkdownExtensions 😁

**Comment by rclabo** [comment]
This is an interesting idea.  You need to add a license to your repository so that developers know if using the project is compatible with their projects.  Using the same license as Markdig (BSD-2) would be a good approach since you build on top of it.

**Comment by xoofx** [comment]
Yeah, no problem for doing that.
