### ISSUE TITLE
[REQ] Lightweight version, without extensions

### ISSUE THREAD

**Issue by dehghani-mehdi** [lunet-io/markdig#372]
Hi,

Is there any plan for this or I do it myself?

**Comment by MihaZupan** [comment]
There's no plan, I do not even see a use case.
It would mean doubling the amount of work for maintaining the library for no real gain.

It is much easier/more rational to analyze specific sections that appear to be more resource-demanding and optimize those as they appear. Even with a rewrite stripping out all extensibility I doubt the performance gain would be worth mentioning.

What is the use case? Markdig is plenty fast enough for gigantic/real-time workloads already. If there's a certain use case that is especially slow with Markdig there are always performance addicts like me floating around that would jump at it.

**Comment by dehghani-mehdi** [comment]
I think extension could be released as separate dll. (the name also says that, they are extensions). 2 projects (core and extension) in one solution. this doesn't add any extra work to the project (and it's easy I think), at the end there will be 2 dlls, e.g: Markdig.dll and Markdig.Extensions.dll

> What is the use case?

Speed is not the problem (at least for me). I'm working on a project which the final size is important, also I don't need any of extensions. the core functionality (_simple_ markdown to html) is enough for me.

**Comment by MihaZupan** [comment]
The entire dll is ~400 kB, that's negligible compared to the runtime itself or any other assets. Do you think reducing the deployment size by 100 kB is worth the effort?

**Comment by dehghani-mehdi** [comment]
Thanks for your time.

As general perspective and as a developer I think the extensions should be in separate project. it add more flexibility to the project, for users and for Markdig's developers. you can test and edit core without worry about extensions and vice versa. users can use extension when they actually needs them.

> Do you think reducing the deployment size by 100 kB is worth the effort?

In normal project I would say no, but for my current project the answer would be yes. 

Anyway you are the boss here and above just my personal opinion, fortunately Markdig is open source (thank you for that), if you are not happy to make this changes, it's okay. I do it myself and I'll try to keep my copy sync with original (as much as I can).

**Comment by xoofx** [comment]
Yeah, we won't remove extensions from core markdig
Our main users are actually relying on these extensions as part of the core experience, so there is little incentive to move them to a separate package.
