### ISSUE TITLE
code block backgound

### ISSUE THREAD

**Issue by zoinkydoink** [lunet-io/markdig#373]
I am using the SyntaxHighlighting extension but it generates a white background for the code block.  I tried passing in StyleDictionarly.DefaultDark but that gave a black background and most of the code is invisible.

I simply would like each code block to have a light grey like you see on every blog post on line

here is the code I am using

    private MarkupString ConvertStringToMarkupString(string value)
    {
        if (!string.IsNullOrWhiteSpace(_content))
        {
            var pipeline = new MarkdownPipelineBuilder()
            .UseAdvancedExtensions()
            .UseSyntaxHighlighting()
            .Build();
            var html = Markdig.Markdown.ToHtml(value, pipeline);
      
            var sanitizedHtml = HtmlSanitizer.Sanitize(html);

            return new MarkupString(sanitizedHtml);
        }

        return new MarkupString();
   
    }

**Comment by xoofx** [comment]
That's a CSS issue/SyntaxHighlighting on your side that should be solved with CSS. Markdig doesn't enforce any rendering rules
