### ISSUE TITLE
Having to pass a pipeline into ToHtml is weird

### ISSUE THREAD

**Issue by dotnetchris** [lunet-io/markdig#38]
Simple fix is to provide an extension ontop of the pipeline

`var html = _mycustomPipeline.ToHtml(markdown);`

```c#
    public static class MarkdigExtensions
    {
        public static string ToHtml(this MarkdownPipeline pipeline, string markdown)
        {
            var html = Markdown.ToHtml(markdown, pipeline);
            return html;
        }
    }
```

Alternative solution, maybe `Build()` returns a type different than MarkdownPipeline and it gives you an instance that does the correct things to have `ToHtml()`.

**Comment by xoofx** [comment]
Sorry I will decline this. I would prefer not to introduce a different high-level API entry point in case you have a pipeline or not, so the current design is preferable as it is the same method. You can still use your extension method in your own project.
