### ISSUE TITLE
Math Symbols

### ISSUE THREAD

**Issue by forgabs** [lunet-io/markdig#412]
Hi! Thanks for this great plugin! Math symbols as defined in Markdig do not work in my case, is it possible to use them?

**Comment by yang-er** [comment]
It cannot translate `$1$` into a math inline. However, `${1}$` is ok.

It refers to `Markdig.Extensions.Mathematics.MathInlineParser`, which comments

> If a $/$$ is not preceded by a whitespace or punctuation, or followed by a digit
> this is a not a math block

To solve this problem, I have copied the parser to my project and remove this restriction.

**Comment by forgabs** [comment]
Thanks! I tried to use ${A_1}$ and would axpect the 1 as subscript, but this doesnt work.

**Comment by yang-er** [comment]
Did you forget applying `UseMathematics()` to `MarkdownPipelineBuilder` ?

**Comment by forgabs** [comment]
Well I have to admit that I did not install markding. I installed the MarkDownViewer++ via the extension control panel in Notepad++ and expected that markding commands are ready to use. Do I have to make additional installations in order to get the Latex math interpreter running.

**Comment by xoofx** [comment]
> Well I have to admit that I did not install markding. I installed the MarkDownViewer++ via the extension control panel in Notepad++ and expected that markding commands are ready to use. Do I have to make additional installations in order to get the Latex math interpreter running.

You should ask this directly to MarkDownViewer folks, as Markdig is not responsible for rendering Latex. The math extension in Markdig is only making sure that it will output blocks that can be recognized by a Latex/Math renderer.
