### ISSUE TITLE
I want to color my console text?

### ISSUE THREAD

**Issue by Layarion** [lunet-io/markdig#414]
I'm using a .net core 3.1 Console App, and I just want to color keywords in my source string from another layer, and have the presentation layer parse the markdown to display colored words.

it's just for normal console text, not html or anything. I'm currently working on my own implementation but would rather not if I don't have to. can I do that with this? I seen that was a .ToHTML piece of code in the readme, is there a like, .ToConsole or .ToValueKeyPairList or something?

**Comment by xoofx** [comment]
> it's just for normal console text, not html or anything. I'm currently working on my own implementation but would rather not if I don't have to. can I do that with this? I seen that was a .ToHTML piece of code in the readme, is there a like, .ToConsole or .ToValueKeyPairList or something?

No there is no built-in like this, you need to develop your own renderer.

**Comment by Layarion** [comment]
If I wanted to pull in a .ToDictionary(string, color) (no idea if this is best route) using MarkDig, would it be difficult for someone new to programming?

**Comment by xoofx** [comment]
It is quite some work, Powershell has done a similar work here https://github.com/PowerShell/PowerShell/tree/master/src/Microsoft.PowerShell.MarkdownRender that you could base your work on.
