### ISSUE TITLE
Empty LiteralInline

### ISSUE THREAD

**Issue by Kryptos-FR** [lunet-io/markdig#42]
The following markdown generates an empty LiteralInline before the line break (notice the empty spaces at the end of the line to force a break) :
```
> *some text* 
> some other text
```

whereas this doesn't:
```
> some text 
> some other text
```

As a workaround, in my renderer, I can check if the content of the literal is empty and ignore it in this case. But IMHO it should be the job of the parser to get rid of it in the first place.
```csharp
if (obj.Content.IsEmpty)
    return;
```

**Comment by xoofx** [comment]
This should be fixed by commit c43d5cc
The fix is only valid for this particular case. There might be other places in the code where a LiteralInline could be ended empty.
