### ISSUE TITLE
Horizontal rule triggers Heading 2

### ISSUE THREAD

**Issue by rpc-scandinavia** [lunet-io/markdig#436]
When converting MarkDown to HTML.
This:
```
Line one.
---
Line two.
```
Becomes:
```
<h2>Line one.</h2>
<p>Line two.</p>
```
Instead of:
```
<p>Line one.</p>
<hr />
<p>Line two.</p>
```

Finally this works:
```
Line one.
***
Line two.
```

I understand that with the H1 and H2 with = and -, the = or - should be the same length as the heading, like this:
```
This is a heading
=================

But this is not
---

YOU
---
```
I do not know whether or not the last one, should be a heading 2 or a horizontal rule. Both have alternatives like ## and ***.

**Comment by MihaZupan** [comment]
This behavior is as defined in the CommonMark spec, see [Example 29](https://spec.commonmark.org/0.29/#example-29).

See [comparison between different parsers](https://babelmark.github.io/?text=Line+one.%0A---%0ALine+two.%0A%0ALine+one.%0A%0A---%0A%0ALine+two.).

The solution is to add blank lines if you use `---`, or to use a different character for the thematic break (`_` or `*`).
```md
Line one.

---

Line two.
```
or
```md
Line one.
___
Line two.
```
turns into
```html
<p>Line one.</p>
<hr>
<p>Line two.</p>
```

**Comment by rpc-scandinavia** [comment]
On this page they show that --- is a horizontal rule:

[https://commonmark.org/help/](https://commonmark.org/help/)

**Comment by rpc-scandinavia** [comment]
And:

> Markdig is a fast, powerful, CommonMark compliant, extensible Markdown processor for .NET.

**Comment by MihaZupan** [comment]
See example 29 I linked above, it explains exactly this case.

> If a line of dashes that meets the above conditions for being a thematic break could also be interpreted as the underline of a setext heading, the interpretation as a setext heading takes precedence. Thus, for example, this is a setext heading, not a paragraph followed by a thematic break:

```md
Foo
---
bar
```

```html
<h2>Foo</h2>
<p>bar</p>
```

**Comment by MihaZupan** [comment]
> And:
> Markdig is a fast, powerful, CommonMark compliant, extensible Markdown processor for .NET.
> Written on this GitHub page.

I agree with that statement 100%

**Comment by rpc-scandinavia** [comment]
Example 29 shows that:

```
you
---
yes
```
Should become H2, but NOT:
```
Fire
---
Truck
```
Only when the upper line is 3 characters long.

**Comment by xoofx** [comment]
See babelmark for how [it behaves](https://babelmark.github.io/?text=you%0A---%0Ayes%0A%0AFire%0A---%0ATruck)

As @MihaZupan said, it is per the spec. All CommonMark implementations are following that.

**Comment by rpc-scandinavia** [comment]
Example 53 is the opposite of what their HELP page shows, it says that "---" and "***" is a horizontal rule. It also shows that the headers use the same length for the text and the "-"s or "="s.

**Comment by xoofx** [comment]
> Example 53 is the opposite of what their HELP page shows, it says that "---" and "***" is a horizontal rule. It also shows that the headers use the same length for the text and the "-"s or "="s.

It's not invalid. You are focusing on a corner case. If you want a `---` to be interpreted as an horizontal line, it would require a separating blank line before the preceding paragraph. 

CommonMark/Markdown is full of corner cases, that's why there is a CommonMark spec for that.

**Comment by MihaZupan** [comment]
It's an example reference table to demonstrate language features. It can't include all specific corner cases of the language - that's why a specification document exists, and it is the spec that is the source of truth as to how parsers should behave.

> It also shows that the headers use the same length for the text and the "-"s or "="s.

That is how it's usually written because it looks better in monospaced font - that does not mean it's required.

**Comment by rpc-scandinavia** [comment]
I understand all that when I read the spec, that there are corner cases and behaviour decisions has been made - but the help page was the first place I looked when trying to test my program, and I expect that is what users do too.

**Comment by rpc-scandinavia** [comment]
Anyway, I just thought there was an error.
Thank you for the great software.

**Comment by xoofx** [comment]
> I understand all that when I read the spec, that there are corner cases and behaviour decisions has been made - but the help page was the first place I looked when trying to test my program, and I expect that is what users do too.

Yeah, it's not really their fault. A help page is not supposed to start to enter corner cases. 
And frankly, Markdown is full of that, that's why sometimes users are confused and also why it's so difficult to get a parser right.
