### ISSUE TITLE
AutoLink for tel: URIs

### ISSUE THREAD

**Issue by saikatguha** [lunet-io/markdig#437]
AutoLinks currently recognizes and links `mailto:...` URIs.

`tel:+1555123456` is the [RFC 3966](https://tools.ietf.org/html/rfc3966) standard ways to link to phone numbers. It is recognized in several browsers (especially on phones) to launch the dialer or to launch facetime etc. See [browser support](https://css-tricks.com/the-current-state-of-telephone-links/).

This is a feature request to add `tel:...` URI auto-linking.

**Comment by MihaZupan** [comment]
Sounds like a reasonable feature
