### ISSUE TITLE
not work layered list

### ISSUE THREAD

**Issue by kripsy** [lunet-io/markdig#445]
if i define list as:

1. first item - this work
2. second item - this work
2.1. this item - this doesn't work

**Comment by xoofx** [comment]
The CommonMark specs doesn't support that.

Also none of the Markdown engine are supporting it has you can see [here](https://babelmark.github.io/?text=1.+first+item+-+this+work%0A2.+second+item+-+this+work%0A2.1.+this+item+-+this+doesn%27t+work)
