### ISSUE TITLE
Bold text not working

### ISSUE THREAD

**Issue by FionaHolder** [lunet-io/markdig#448]
I have a very simple test set up and it doesn't seem to be picking up on emphasis at all. Am I configuring or using this wrong? It seems like a very basic use case. 

I'm using the Nuget package in ASP.NET Core: `Markdig.Markdown.ToHtml(markdown);`

The markdown is `## Big heading\nHello this is some text on my page. **This bit is bold. **\n`

The HTML I get back is `<h2>Big heading</h2>\n<p>Hello this is some text on my page. **This bit is bold. **</p>\n`

**Comment by xoofx** [comment]
It is expected as per CommonMark specs: the space just before the trailing `**` must be removed, you can try it [here](https://babelmark.github.io/?text=%23%23+Big+heading%0A%0AHello+this+is+some+text+on+my+page.+**This+bit+is+bold.+**)

```markdown
## Big heading

Hello this is some text on my page. **This bit is bold.**
```
