### ISSUE TITLE
MArkdig produce error "Operation could destabilize the runtime." on remote IIS web server

### ISSUE THREAD

**Issue by toldino** [lunet-io/markdig#450]
`> PEVerify.exe markdig.dll` 

returns more than 300 errors similar to this:  

> [MD]: Error: Token 0x0200012f following ELEMENT_TYPE_CLASS (_VALUETYPE) in signature is a ValueType (Class,respectively). [token:0x1B0000AE]

Because of these errors markdig is unusable on many (Italian) web servers due to the error:

```
Operation could destabilize the runtime.

Description: An unhandled exception occurred during the execution of the current
web request. Please review the stack trace for more information about the error
and where it originated in the code.

Exception Details: System.Security.VerificationException: Operation could
destabilize the runtime.
```
Any work around?

**Comment by xoofx** [comment]
Markdig is using unsafe code so it can't be verified. 
About this error I can't tell, but PEVerify is barely usable today on most OSS libraries that are using structs...etc
So we can't do anything about this. You should try to find a provider that allows you to host .NET Core ASP.NET, you won't get such errors (e.g Azure)
