### ISSUE TITLE
Maths parsing problem

### ISSUE THREAD

**Issue by NaolShow** [lunet-io/markdig#451]
Hi everyone, I have a problem with the parsing of the mathematics.
For exemple if I have this in markdown:

```
# Testing mathematics
$0$ or $2x$
```

The title will be parsed correctly, but I'll also have: $0$ or $2x$
(In the html source code: ```<p>$0$ or $2x$</p>```)

I'm using a pipeline:
```var Pipeline = new MarkdownPipelineBuilder().UseAdvancedExtensions().UseBootstrap().UseEmojiAndSmiley().UseSoftlineBreakAsHardlineBreak().Build();```

Do you know what is the problem ?
Thanks a lot ! :)

**Comment by xoofx** [comment]
Looks like a bug but can't recall what would be the cause of the problem. It seems to work fine with spaces around the number (e.g `$ 0 $`)
Don't have time to investigate issues these days for markdig, so if you feel to investigate this, you are welcome :)

**Comment by davidackroyd99** [comment]
I will have a look and see if I can raise a pr
