### ISSUE TITLE
Reverse parser

### ISSUE THREAD

**Issue by LukeTOBrien** [lunet-io/markdig#462]
Hello,

I need to do this for a project I'm working on and I just thought I would ask here as I know you guys are helpful and in the chance that there might be a way.  
I would like to take an HTML string and convert that string to Markdown.  
For eg:  
`<h3>Heading</h3>` to `### Heading`  
Or more complex:
```
<ul>
<li>123</li>
<li>abc</li>
</ul>
```
to
```
* 123
* abc
```

Can you think of a way to achieve this?  
I was going to do it manually using string manipulation.

Thanks

Luke

**Comment by MihaZupan** [comment]
This is effectively a dupe of #91, see Alexandre's response there https://github.com/lunet-io/markdig/issues/91#issuecomment-277191539

**Comment by LukeTOBrien** [comment]
Thanks,  
I never heard of AngleSharp, I am using HtmlAgilityPack inn my project... I will see what I can do
