### ISSUE TITLE
Can the `IndentCount` of `FenceCode` public?

### ISSUE THREAD

**Issue by 928PJY** [lunet-io/markdig#463]
What we are trying to do is to convert the AST back to markdown file, but we found there is some information lost or cannot be accessed. One of that is the `IndentCount` in `FenceCodeBlock`, which is an [internal property](https://github.com/lunet-io/markdig/blob/master/src/Markdig/Syntax/FencedCodeBlock.cs#L56), is that possible to export that?

**Comment by MihaZupan** [comment]
Seems reasonable, I don't see a problem with exposing it

**Comment by 928PJY** [comment]
PR created
