### ISSUE TITLE
Setext headings in blockquotes

### ISSUE THREAD

**Issue by hamvocke** [lunet-io/markdig#465]
There seems to be a problem with [Setext headings](https://spec.commonmark.org/0.29/#setext-heading) used within blockquotes.

Take this markdown input:

```
> Hello
> ----
> this is some other text
```

Running this on [babelmark](https://babelmark.github.io/?text=%3E+Hello%0A%3E+----%0A%3E+this+is+some+other+text) shows that most renderers will generate a blockquote that contains a heading and a paragraph. Markdig, however, creates a blockquote that contains a paragraph, a horizontal rule and another paragraph.

The CommonMark spec is not absolutely explicit about this case but [generally states](https://spec.commonmark.org/0.29/#example-29) that `---` characters should be treated as a Setext heading if they can be interpreted that way.

Is this something that should be fixed in Markdig to be closer to what other Markdown renderers are doing?

**Comment by xoofx** [comment]
It's definitely a bug, don't have time to look at this, but in case you have, PR welcome.
