### ISSUE TITLE
Lazy quoteline after empty quoteline

### ISSUE THREAD

**Issue by generateui** [lunet-io/markdig#480]
```
>
p
```
should be parsed as one quoteblock, yet it is parsed as a quoteblock and then paragraph block after. 

See also: https://babelmark.github.io/?text=%3E%0Ap%0A. Note that about half of markdown parsers have this bug. I conclude this is a bug because of two examples in the spec:
- https://spec.commonmark.org/0.29/#example-202
- https://spec.commonmark.org/0.29/#example-209

**Comment by xoofx** [comment]
Well, the spec is maybe unclear on that particular case, but all CommonMark implementations are behaving the same. Lazyness ness (so continuing a blockquote on the following paragraph) can only happen if the starting blockquote has already a content paragraph.
If you disagree with this rule you should ask to the commonmark forum as it is a edge case that might need a clarification in the specs (but I think the lazyness description in the spec should cover this part).

**Comment by generateui** [comment]
According to babelmark, there's a roughly 50% split in Markdown implementations. Will do your suggestion, as the 50/50 interpretation clearly shows ambiguity/unclarity here.

**Comment by generateui** [comment]
See discussion in markdown spec forum: https://talk.commonmark.org/t/unclear-paragraph-after-empty-quoteline-in-quote-block/3652

**Comment by xoofx** [comment]
> According to babelmark, there's a roughly 50% split in Markdown implementations. Will do your suggestion, as the 50/50 interpretation clearly shows ambiguity/unclarity here.

Yes, and all the 50% implementations are not CommonMark, so that explain why there is this split. All 100% CommonMark implementations are following the same rule.

**Comment by xoofx** [comment]
If the specs make it clear in a future version, we will fix it. For now, we are all following the specs.

**Comment by generateui** [comment]
Ah, that makes sense. I assumed all implementation on babelmark implemented the commonmark spec.
