### ISSUE TITLE
"Cannot add this block" 0.21.1 -> 0.22

### ISSUE THREAD

**Issue by AndersMad** [lunet-io/markdig#484]
I get **"Cannot add this block as it as already attached to another container (block.Parent != null)"** after updating from 0.21.1 to 0.22 (nothing else changed)..

I'm a bit lost - any hints?

**Comment by AndersMad** [comment]
This seems to be happening in Microsoft.DocAsCode.MarkdigEngine.Extensions.MarkdownDocumentVisitor:
``` 
Markdig.Helpers.ThrowHelper.ArgumentException(String message)
Markdig.Syntax.ContainerBlock.set_Item(Int32 index, Block value)
Microsoft.DocAsCode.MarkdigEngine.Extensions.MarkdownDocumentVisitor.RewriteContainerBlock(ContainerBlock blocks)
Microsoft.DocAsCode.MarkdigEngine.Extensions.MarkdownDocumentVisitor.Visit(MarkdownDocument document)
Markdig.Parsers.ProcessDocumentDelegate.Invoke(MarkdownDocument document)
```

**Comment by xoofx** [comment]
You should report that on docfx repo then.

**Comment by xoofx** [comment]
In Markdig 0.22 we can no longer reuse a same node in multiple places

**Comment by AndersMad** [comment]
ok, mark me - I'll dig into it later :) closing this

**Comment by AndersMad** [comment]
I misread this - this is merged into the v3 branch - not current release.. FYI if someone else gets here: https://github.com/dotnet/docfx/pull/6616

**Comment by mungojam** [comment]
a newbie question on this then. If I want to just take some blocks from one document and copy them to another document, how is that possible? Do I have to artificially remove them from the original?
