### ISSUE TITLE
Question: Determine Word Count?

### ISSUE THREAD

**Issue by Mike-E-angelo** [lunet-io/markdig#485]
Greetings... thank you for making this great library!

In my case, I am looking for a Markdown parser/library/api that can quickly tell me the line count and word count of a given Markdown document.  I see that there is a `MarkdownDocument.LineCount` so that takes care of one of the requirements.  

Is there a way of determining the word count of a document in a similar fashion?  I see there's a way of iterating through the document via #381, so I will be attempting to do this, but wanted to quickly ping here to see if there is an easier/more obvious way of doing so.

Thank you for any assistance you can provide. 👍

**Comment by xoofx** [comment]
It's not straightforward to go through all the AST to collect words. Why don't you perform that on the input string directly with a regex? 
- count words: `Regex.Matches(markdownText, @"\b\w+\b").Count`
- count lines: `Regex.Matches(markdownText, "\n").Count`

**Comment by Mike-E-angelo** [comment]
That's actually what I am doing with plain text documents, @xoofx. 😁  The thought did occur to do the same with Markdown documents but wanted to ensure there wasn't some obvious feature I was overlooking with the API here to be more accurate and/or engrained, for lack of a better word.

So, it looks like I will go with `RegEx`, then.  Thank you for your time and input!
