### ISSUE TITLE
UrlSpan not assigned for image references

### ISSUE THREAD

**Issue by madskristensen** [lunet-io/markdig#51]
The `LinkInline` object has `UrlSpan` == null for image references like this:

`[image]: images/image.png`

/cc https://github.com/madskristensen/MarkdownEditor/commit/2b3c53e3fdd4e474fa377bb8301842a8707029f0

**Comment by xoofx** [comment]
Should be fixed by commit  	2e6ab67

**Comment by xoofx** [comment]
Right, completely forgot this one.

**Comment by xoofx** [comment]
hm, looking at it, `LinkReferenceDefinition` should be fine. Where is exactly the problem @madskristensen ?

**Comment by xoofx** [comment]
Fixed via  	79348eb
