### ISSUE TITLE
Command line version

### ISSUE THREAD

**Issue by mike-ward** [lunet-io/markdig#53]
Is there a command line version? If not would you accept a pull request for one?

**Comment by xoofx** [comment]
Out of curiosity, what is your usecase?

**Comment by Sergey-Terekhin** [comment]
Hi!
For example, batch convert md files to html for user guides
For now we need to write such utility by self, but if it is provided by parser's author, it will be better I think

**Comment by xoofx** [comment]
Such tools are part of compositing engines (using a templating system), as you need to layout the files, i.e. embrace the generated markdown with proper html pre and post prologue + you need to have the proper CSS/JS files/libraries around to make sure that the rendering will be pleasant and functional.

So it is a bit out of the scope of a Markdown library. This is more related to a documentation/static website generators. I'm working on such a generator called [lunet](https://github.com/lunet-io/lunet) but it is not yet finished/ready. There are also other established options like [Wyam](https://github.com/Wyamio/Wyam) that are using markdig to layout files.

Closing this issue for now, as I don't expect to add such a feature to the core library.
