### ISSUE TITLE
DefinitionList Extension does not allow custom attributes on description elements

### ISSUE THREAD

**Issue by aKzenT** [lunet-io/markdig#59]
For our project, I'm writing an extension which sets custom attributes on some Markdown Elements, which should be rendered in the resulting HTML (e.g. for styling).

This works fine for almost all elements (paragraphs, lists, etc.), but fails for the definition list extension, because it will always write an empty <dd> element without honoring any attributes set on the description paragraph.

There is also currently no good workarround for this issue. I would currently need to copy the complete extension only to change this single part.

Best regards,
Thomas

**Comment by xoofx** [comment]
Hm weird, the code [here](https://github.com/lunet-io/markdig/blob/master/src/Markdig/Extensions/DefinitionLists/HtmlDefinitionListRenderer.cs#L20) and [there](https://github.com/lunet-io/markdig/blob/master/src/Markdig/Extensions/DefinitionLists/HtmlDefinitionListRenderer.cs#L44) does write the attributes. Could you elaborate how you add these attributes?

**Comment by aKzenT** [comment]
It't the "renderer.Write("<dd>");" that's causing the problem for me.

**Comment by xoofx** [comment]
Ah good catch, you can make a PR if you want to fix this.
