### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by sbrickey** [lunet-io/markdig#6]
so, having only just discovered this... and wanting to see if i could cause issues to the parsers...

I used this:
    this \*is\* a \*\*test\*\* of various \~markdown\~\~impl\^ementations\^\~\~.\~

while yours is admittedly the best (among the various results in babelmark), it only "works" when the period exists at the end (separator between the closing ~~ and ~). I say "works" because i've not actually checked the commonmark spec for how it should be handled, rather it's based on what i'd _expect_ it to do.

I'll let you determine how my example fits into everything... just wanted to mention it. (also, have fun seeing how the other parsers handle it! yours was by far the closest)

otherwise, keep up the good work :)

**Comment by xoofx** [comment]
This is a CommonMark spec behaviour, though if you look at an equivalent with simple emphasis on [`this is an emphasis *test***`](http://babelmark.github.io/?text=this+is+an+emphasis+*test***) you will see that there is a trailing `**`

Not strictly related to this case, but CommonMark folks are thinking about changing the behaviour of emphasis for some [corner cases](https://talk.commonmark.org/t/emphasis-strong-emphasis-corner-cases/2123)
