### ISSUE TITLE
Pipetable left column alignment

### ISSUE THREAD

**Issue by rainmaker2k** [lunet-io/markdig#62]
The [HtmlTableRenderer](https://github.com/lunet-io/markdig/blob/fa281f1ca11c7b848509b2928cea2526f0fd74fe/src/Markdig/Extensions/Tables/HtmlTableRenderer.cs) seems to ignore the left alignment property in the ColumnDefinition. The default user styles for the table header in at least Chrome will default it to center.

Can this be changed to include `text-align: left` in the `<th` element?

**Comment by xoofx** [comment]
This is fixed by commit  	d5e6f17.

The behavior is:
- no align => the HTML default applies (th center, td left), style is not applied
- align defined => th and td get the same style alignment
