### ISSUE TITLE
Extension request: Automatically convert urls to hyperlinks

### ISSUE THREAD

**Issue by ferventcoder** [lunet-io/markdig#64]
Forgive me but with not much documentation and a short trip through the source I didn't see this. If it is there already, that would be great! 

I just found this library and it looks excellent! I'm converting over from MarkdownSharp. One of the things it offers is the ability to automatically convert urls to hyperlinks. I'd love to do the same with this library.

**Comment by xoofx** [comment]
Good suggestion, forgot to implement this. This is fixed by 95641e5 
up-for-grabs in the up-coming 0.9.0 version 😉

**Comment by ferventcoder** [comment]
Awesome, thanks!
