### ISSUE TITLE
HTML Link with URL text tries to render twice when AutoLink() is on

### ISSUE THREAD

**Issue by RickStrahl** [lunet-io/markdig#65]
If you have a link like this when Autolink is enabled: 

`<a href="http://somewhere.com" target="top">http://somewhere.com</a>`

the parser produces:

`http://somehwere.com</a>`

Looks like AutoLink needs to ensure it's not already inside of a link or link text before expanding a URL.

**Comment by xoofx** [comment]
Ah 😨  sorry for this regression 😅 
This should be fixed by commit 81b8dce (with relevant additional tests)
I have included also another case with regular markdown links that could also interfere
