### ISSUE TITLE
MarkdownPipelineBuilder thread safe?

### ISSUE THREAD

**Issue by SimonCropp** [lunet-io/markdig#69]
so a MarkdownPipeline is not thread safe. but is a MarkdownPipelineBuilder thread safe?

**Comment by xoofx** [comment]
The MarkdownPipeline should be thread safe, the builder is not (and will unlikely be)

**Comment by xoofx** [comment]
Note that when I say that `MarkdownPipeline` is thread safe, it is thread safe for normal usage 😅 Manipulating indirectly the parsers registered to the pipeline (changing some properties...etc.) will not be thread safe. But if you use the `MarkdownPipelineBuilder` API in a regular way, you should not have any problems.
