### ISSUE TITLE
Setting for not wrapping the parsed HTML in <p> tags

### ISSUE THREAD

**Issue by hemantkd** [lunet-io/markdig#70]
Hi @xoofx ,
Is there a setting or option that I can use so that when I'm doing:
`Markdown.ToHtml("This is a text with some *emphasis*")`,
I get the parsed output as `This is a text with some <em>emphasis</em>` 
instead of `<p>This is a text with some <em>emphasis</em></p>`?

**Comment by xoofx** [comment]
nothing like this. I guess you can remove manually the `<p>...</p>` as a simple post process on the output string if you are sure that it doesn't contain anything more than a single paragraph

**Comment by hemantkd** [comment]
Thanks for you help.

**Comment by jjxtra** [comment]
If you do this, don't use regex. You have to actually parse the html, make sure there is a global <p>...</p> and only remove in that case. For some text with newlines, you will get <p>...</p><p>...</p> in which case you may want to leave it alone.

**Comment by xoofx** [comment]
> If you do this, don't use regex. You have to actually parse the html, make sure there is a global

Could you avoid commenting on 3 different issues the same problem? It's very annoying to receive 3 notifications for the same topics we already responded that are closed.
