### ISSUE TITLE
Bold text not working 

### ISSUE THREAD

**Issue by WnagoiYy** [lunet-io/markdig#728]
I can't understand why this cannot be parsed, there are no spaces, and I'm not sure if it's in Chinese?

[babelmark](https://babelmark.github.io/?text=%23%23+Big+heading%0A%0A**%E9%BA%BB%E9%BB%84%E5%96%84%E8%83%BD%E5%8F%91%E6%B1%97%E3%80%81%E5%B9%B3%E5%96%98%EF%BC%8C%E5%85%BC%E8%83%BD%E5%88%A9%E6%B0%B4%EF%BC%8C%E4%B8%BA%E8%82%BA%E7%BB%8F%E4%B8%93%E8%8D%AF%E3%80%82**%E4%B8%BA%E9%BA%BB%E9%BB%84%E7%A7%91%E5%A4%9A%E5%B9%B4%E7%94%9F%E8%8D%89%E6%9C%AC%E7%8A%B6%E5%B0%8F%E7%81%8C%E6%9C%A8%E8%8D%89%E9%BA%BB%E9%BB%84%E6%88%96%E6%9C%A8%E8%B4%BC%E9%BA%BB%E9%BB%84%E5%92%8C%E4%B8%AD%E9%BA%BB%E9%BB%84%E7%9A%84%E8%8D%89%E8%B4%A8%E8%8C%8E%E3%80%82%E5%8E%BB%E8%8A%82%EF%BC%8C%E5%90%8D%E5%87%80%E9%BA%BB%E9%BB%84%EF%BC%9B%E6%8D%A3%E7%BB%92%EF%BC%8C%E5%90%8D%E9%BA%BB%E9%BB%84%E7%BB%92%E3%80%82%E7%94%9F%E7%94%A8%E6%88%96%E8%9C%9C%E7%82%99%E7%94%A8%E3%80%82)

**Comment by WnagoiYy** [comment]
<img width="793" alt="Snipaste_2023-08-11_00-31-17" src="https://github.com/xoofx/markdig/assets/16523520/31dcfae7-b147-4de3-b6c5-d6cedec9a825">

**Comment by MihaZupan** [comment]
This is the relevant section of the commonmark spec: https://spec.commonmark.org/0.30/#emphasis-and-strong-emphasis



> A [right-flanking delimiter run](https://spec.commonmark.org/0.30/#right-flanking-delimiter-run) is a [delimiter run](https://spec.commonmark.org/0.30/#delimiter-run) that is (1) not preceded by [Unicode whitespace](https://spec.commonmark.org/0.30/#unicode-whitespace), and either (2a) not preceded by a [Unicode punctuation character](https://spec.commonmark.org/0.30/#unicode-punctuation-character), or (2b) preceded by a [Unicode punctuation character](https://spec.commonmark.org/0.30/#unicode-punctuation-character) and followed by [Unicode whitespace](https://spec.commonmark.org/0.30/#unicode-whitespace) or a [Unicode punctuation character](https://spec.commonmark.org/0.30/#unicode-punctuation-character). For purposes of this definition, the beginning and the end of the line count as Unicode whitespace.

It's essentially saying that the closing `**` (right-flanking) have some rules around what characters can be present just before and just after it.

In your case, you have a `。` ("ideographic full stop") character right before the `**`.
This character is a punctuation character, so if you want the `**` to be considered, it must also be followed by a whitespace or punctuation.

If you insert a space right after `**`, you should see it working again.

**Comment by tats-u** [comment]
- #890
