### ISSUE TITLE
Table rendering issue

### ISSUE THREAD

**Issue by maulwuff** [lunet-io/markdig#73]
This is my md:
```
| abc | def | ghi |
|---|---|---|
| 1 | 2 | 3 |
| 1 | 2 | ~3 |
```

which will render an empty cell in the second data row. It looks like I would have typed
```
| 1 | 2 |   | ~3 | 
```

v0.10.2

**Comment by xoofx** [comment]
Thanks for the report, this is fixed by commit f11d803
