### ISSUE TITLE
Consider introducing generic extension registry method to MarkdownPipelineBuilder

### ISSUE THREAD

**Issue by christophano** [lunet-io/markdig#79]
While I like having specific extension methods to load specific extensions onto the pipeline builder, it is also handy not to have to create an extension method for _every_ extension I create.
To that end, I tend to use a single extension method for registering simple extensions.

Would you consider including this method on the `MarkdownPipelinBuilder` class itself? Happy to complete a pull request for this.

Method:
```cs
public MarkdownPipelineBuilder Use<TExtension>() where TExtension : class, IMarkdownExtension, new()
{
    Extensions.AddIfNotAlready<TExtension>();
    return this;
}
```

Usage:
```cs
var pipeline = new MarkdownPipelineBuilder()
    .Use<AwesomeExtension>()
    .Build();
```

**Comment by xoofx** [comment]
Sure it is a good idea to add this.
