### ISSUE TITLE
Emoji parser enforces a space delimiter

### ISSUE THREAD

**Issue by johnsimons** [lunet-io/markdig#88]
I am just wondering why the emoji parser enforces the space delimiter in https://github.com/lunet-io/markdig/blob/master/src/Markdig/Extensions/Emoji/EmojiParser.cs#L84-L88.

I guess I would like to remove this restriction so I can have md like:
```md
A sentence :smiley:.
Or another sentence :smiley:, more text.
```

**Comment by xoofx** [comment]
I don't remember exactly why I required this in the first place. Maybe that's not a necessary condition, but will need some tests...

**Comment by johnsimons** [comment]
@xoofx submitted #89, I have added a couple more tests, but you may want more, not sure ?
