### ISSUE TITLE
Span not set for EmphasisInline and LinkInline

### ISSUE THREAD

**Issue by madskristensen** [lunet-io/markdig#9]
The `Span` property always return a `0,0` span for EmphasisInline and LinkInline.

This might be the same for other inline objects, but I've only tested for these two types

**Comment by xoofx** [comment]
You need to configure the pipeline with option `pipelineBuilder.UsePreciseSourceLocation().Build()` See for example the [tests](https://github.com/lunet-io/markdig/blob/master/src/Markdig.Tests/TestSourcePosition.cs#L688)

**Comment by madskristensen** [comment]
Awesome. That worked!!
