### ISSUE TITLE
[Question] Adding specific attributes NOT related to HTML output

### ISSUE THREAD

**Issue by bambooLoutre** [lunet-io/markdig#94]
Hello,

I'm currentlly using Markdown files into an app, without the need of HTML generation.
I'd like to add some kind of header to the markdown file, something like

```
[HEADER Title="Test01" Format="theFormat" Author="theAuthor"]
# THIS IS A H1 TEST
This is a test
```

Is there a way to handle this into Markdig without having to pre-parse the document by hand ?

The syntax in the example is not a requirement. Any syntax can do the job.

Thanks for your help

**Comment by xoofx** [comment]
There is no extensions like this in markdig, as metadata are usually quite process dependent, so they are handled at a higher level (text templating layer, header data...etc.) Usually you use something like a YAML frontmatter, but whatever fits your needs (a simple parser for a first line can be sometimes a simpler option)

**Comment by bambooLoutre** [comment]
Oh, YAML seems a good choice, I'll dig it. Thanks
