### ISSUE TITLE
How can I change the rendering of ID of a Header element?

### ISSUE THREAD

**Issue by asapostolov** [lunet-io/markdig#95]
I'm converting Cyrillic alphabet markdown to html. When h2/3/4/5 elements are made when the alphabet is  Latin the header's text is converted to id in a proper way. However when the alphabet is Cyrillic the id-s of the headers become `section-1`, `section-2`, `section-3` etc. 

How can I modify that behavior to be able to generate proper Cyrillic ids?

**Comment by xoofx** [comment]
By default, the auto-identifier tries to convert to ASCII using some character correspondence. Can you post an example headers with cyrillic alphabet?

Otherwise, you should be able to disable the ASCII conversion:

```csharp
// Remove the previous AutoIdentifierExtension
pipelineBuilder.Extensions.Remove(pipeline.Extensions.Find<AutoIdentifierExtension>());
// Add AutoIdentifier extension with only AutoLink option
pipelineBuilder.UseAutoIdentifiers(AutoIdentifierOptions.AutoLink);
```

**Comment by asapostolov** [comment]
Here's an Cyrillic Header

`
Здравейте, аз съм Петър и съм програмист
`

When I did as you said - I removed the extension and used `AutoLink` the conversion - the Ids seemed to start converting properly in Cyrillic. Thanks!
