### ISSUE TITLE
Emoji followed by punctiation fail

### ISSUE THREAD

**Issue by RickStrahl** [lunet-io/markdig#98]
The following doesn't render Emoji as expected:

```markdown
### Works
Smile: :smile:

Smile: :grin: .

### Doesn't work
Smile: :smile:.

Smile: (What? :smile:)

Smile: -:smile:
```

Produces:

![image](https://cloud.githubusercontent.com/assets/1374013/23281902/1ac4d03c-f9c3-11e6-97cf-99724cdd187b.png)

**Comment by xoofx** [comment]
This one should have been fixed from latest already. Are you using 0.10.5?

**Comment by Kryptos-FR** [comment]
@xoofx Could be nice if [babelmark](https://babelmark.github.io/?text=%23%23%23+Works%0ASmile%3A+%3Asmile%3A%0A%0ASmile%3A+%3Agrin%3A+.%0A%0A%23%23%23+Doesn%27t+work%0ASmile%3A+%3Asmile%3A.%0A%0ASmile%3A+(What%3F+%3Asmile%3A)%0A%0ASmile%3A+-%3Asmile%3A) could render the emojis :smile:

**Comment by xoofx** [comment]
So I assume that it was already fixed

**Comment by RickStrahl** [comment]
Sorry yeah it was definitely working in 0.10.6. I was on 0.10.4 before (i think) so that was not working.
