### ISSUE TITLE
Image References?

### ISSUE THREAD

**Issue by RickStrahl** [lunet-io/markdig#99]
Wondering if Image References ([as per](https://daringfireball.net/projects/markdown/syntax#img ) are working in Markdig?  

This does not work for me:

```markdown
![](configicons)

...

[configicons]: configicons.png "title for image"
```

I noticed #51 talks about image references, but not sure where that comes in. Could I just be missing an extension (although I have most enabled)?

**Comment by xoofx** [comment]
The specs of [Images in CommonMark](http://spec.commonmark.org/0.27/#images) expect that after paranthesis after a link `(...)` are an URL only. You need to use bracket `[...]` for the id, as you can verify this on [babelmark3](https://babelmark.github.io/?text=!%5B%5D%5Bconfigicons%5D%0A%0A...%0A%0A%5Bconfigicons%5D%3A+configicons.png+%22title+for+image%22)

```md
![][configicons]

...

[configicons]: configicons.png "title for image"
```

**Comment by RickStrahl** [comment]
Duh - sorry my bad :-) Thanks and it works great.

Good use case for this BTW: Embedding base64 encoded image content at the ends of the document.

**Comment by xoofx** [comment]
Note that you can also use `![configicons]` alone (it will just set the alttext to `configicons`)

> Good use case for this BTW: Embedding base64 encoded image content at the ends of the document.

Indeed, good idea!
